-- EXAMPLE ONLY. Requires DBA review. Never execute automatically.
CREATE USER JSAMS_DEV
IDENTIFIED BY "<PASSWORD_PLACEHOLDER>"
DEFAULT TABLESPACE "<TABLESPACE_PLACEHOLDER>"
TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION TO JSAMS_DEV;
GRANT CREATE TABLE TO JSAMS_DEV;
GRANT CREATE SEQUENCE TO JSAMS_DEV;
GRANT CREATE VIEW TO JSAMS_DEV;
GRANT CREATE PROCEDURE TO JSAMS_DEV;

ALTER USER JSAMS_DEV
QUOTA UNLIMITED ON "<TABLESPACE_PLACEHOLDER>";
