export const legacyHazardPrompts = [
  { code: 'HARD_HAT', label: 'Hard hat' },
  { code: 'DISPOSABLE_COVERALL', label: 'Disposable coverall' },
  { code: 'USE_OF_LADDER', label: 'Use of ladder' },
  { code: 'MSDS', label: 'MSDS' },
  { code: 'WELL_CONTROL_AGREED', label: 'Well control procedures agreed' },
  { code: 'HEAT_RESISTANT_GLOVES', label: 'Gloves (heat resistant/other)' },
  { code: 'SAFETY_GOGGLES', label: 'Safety goggles' },
  { code: 'FALL_PROTECTION_HARNESS', label: 'Fall protection/ Safety Harness' },
  { code: 'GAS_TEST', label: 'Gas test' },
  { code: 'THIRD_PARTY_INVOLVED', label: 'Third party involved' },
  { code: 'IMPACT_GLOVE', label: 'Impact Glove' },
  { code: 'SAFETY_SHIELDS', label: 'Safety shields' },
  { code: 'SIGNS_BARRIERS', label: 'Signs/barriers' },
  { code: 'RESCUE_PLAN_REQUIRED', label: 'Rescue plan required' },
  { code: 'FIRE_FIGHTING_EQUIPMENT', label: 'Fire-fighting equipment' },
  { code: 'SAFETY_BOOTS_RUBBER', label: 'Safety boots/shoe (rubber)' },
  { code: 'HEARING_PROTECTION', label: 'Hearing protection' },
  { code: 'ENV_HAZARDS_REVIEWED', label: 'Environment Hazards Reviewed' },
  { code: 'SIMOPS', label: 'Simultaneous operations (SIMOPS)' },
  { code: 'ISOLATIONS_REQUIRED', label: 'Isolations required' },
  { code: 'SAFETY_GLASSES', label: 'Safety glasses' },
  { code: 'DUST_MASK', label: 'Dust mask' },
  { code: 'WEATHER_REPORTS', label: 'Weather reports discussed' },
  { code: 'RADIO_BANKSMAN_COMMS', label: 'Communication (Radio/Banksman)' },
  { code: 'LIFEJACKET_WORK_VEST', label: 'Lifejacket/Work Vest' },
] as const;

export const supersededDevelopmentPromptCodes = ['ENERGY', 'DROPPED', 'PINCH'] as const;
