export const pvDrillingToolScope = 'GLOBAL' as const;
export const pvDrillingToolCategory = { code: 'JSA_TOOLS', name: 'JSA Tools' } as const;

export const pvDrillingTools = [
  { code: 'HARD_HAT', name: 'Hard Hat' },
  { code: 'IMPACT_GLOVES', name: 'Impact Gloves' },
  { code: 'GLOVES_OTHER', name: 'Gloves other (Chemical/Weld/Mech/Elect)' },
  { code: 'SAFETY_BOOTS_SHOES', name: 'Safety Boots / Shoes' },
  { code: 'SAFETY_GLASSES', name: 'Safety Glasses' },
  { code: 'DISPOSABLE_COVERALLS', name: 'Disposable Coveralls' },
  { code: 'HEARING_PROTECTION', name: 'Hearing Protection' },
  { code: 'CHEMICAL_APRON', name: 'Chemical Apron' },
  { code: 'RESPIRATOR_DUST_MASK', name: 'Respirator/Dust Mask' },
  { code: 'DISPOSABLE_COVERALL', name: 'Disposable Coverall' },
  { code: 'SAFETY_GOGGLES', name: 'Safety Goggles' },
  { code: 'FACE_SHIELD', name: 'Face Shield' },
  { code: 'USE_OF_LADDER', name: 'Use of Ladder' },
  { code: 'LANYARDED_TOOLS', name: 'Lanyarded Tools (DO Tools f/ height)' },
  { code: 'SAFETY_HARNESS_RIDING_BELT', name: 'Safety Harness / Riding Belt' },
  { code: 'INERTIA_REEL', name: 'Inertia Reel' },
  { code: 'RESCUE_TRIPOD', name: 'Rescue Tripod' },
  { code: 'BA_SET', name: 'BA Set' },
  { code: 'SIGNS_BARRIERS', name: 'Signs / Barriers' },
  { code: 'MSDS', name: 'MSDS' },
  { code: 'GAS_TEST', name: 'Gas Test' },
  { code: 'RESCUE_PLAN_REQUIRED', name: 'Rescue Plan required' },
  { code: 'SIMOPS', name: 'SIMOPS' },
  { code: 'BANKSMAN', name: 'Banksman' },
  { code: 'RADIOS', name: 'Radios' },
  { code: 'THIRD_PARTY_INVOLVED', name: '3rd Party Involved' },
  { code: 'FIRE_EXTINGUISHER_HOSE', name: 'Fire Extinguisher /Hose' },
  { code: 'ISOLATIONS_REQUIRED', name: 'Isolations Required' },
  { code: 'LIFEJACKET', name: 'Lifejacket' },
  { code: 'WORK_VEST', name: 'Work Vest' },
  { code: 'FLUKE_METER', name: 'Fluke Meter (Elect tester)' },
  { code: 'WEATHER_REPORTS_DISCUSSED', name: 'Weather Reports Discussed' },
  { code: 'ENVIRONMENT_HAZARDS_REVIEWED', name: 'Environment Hazards Reviewed' },
  { code: 'VENTILATION_REQUIRED', name: 'Ventilation required' },
  { code: 'STANDBY_BOAT_REQUIRED', name: 'Standby Boat required' },
  { code: 'RADIO_SILENCE_REQUIRED', name: 'Radio Silence required' },
  { code: 'RIG_ANNOUNCEMENT_REQUIRED', name: 'Rig Announcement required' },
  { code: 'STANDBY_MAN_FIRE_WATCH', name: 'Standby man / Fire watch' },
  { code: 'AIR_TOOLS', name: 'Air tools' },
  { code: 'HAND_TOOLS', name: 'Hand tools' },
  { code: 'LIFTING_EQUIPMENT', name: 'Lifting Equipment' },
  { code: 'SLINGS', name: 'Slings' },
  { code: 'SHACKLES', name: 'Shackles' },
  { code: 'CHAIN_HOISTS', name: 'Chain Hoists' },
  { code: 'LEVER_HOISTS', name: 'Lever Hoists' },
  { code: 'PUSH_PULL_STICKS', name: 'Push/Pull Sticks' },
  { code: 'CRANE_PENNANTS', name: 'Crane Pennants' },
  { code: 'SAFETY_HANG_OFF_PENNANTS', name: 'Safety hang off pennants' },
  { code: 'TAG_LINES', name: 'Tag Lines' },
  { code: 'ROLLER_RESCUE', name: 'Roller Rescue' },
  { code: 'RESCUE_INERTIA_REEL', name: 'Rescue Inertia Reel' },
  { code: 'RESCUE_REEL_TRIPOD', name: 'Rescue Reel/Rescue Tripod' },
  { code: 'KNIFE', name: 'Knife' },
] as const;
