export const pvDrillingPositionScope = 'GLOBAL' as const;

export const pvDrillingPositions = [
  { code: 'OIM', name: 'OIM' },
  { code: 'SENIOR_TOOLPUSHER', name: 'Senior Toolpusher' },
  { code: 'NIGHT_TOOLPUSHER', name: 'Night Toolpusher' },
  { code: 'DAY_TOOLPUSHER', name: 'Day Toolpusher' },
  { code: 'DRILLER', name: 'Driller' },
  { code: 'PUMPMAN', name: 'Pumpman' },
  { code: 'DERRICKMAN', name: 'Derrickman' },
  { code: 'FLOORMAN', name: 'Floorman' },
  { code: 'ROUSTABOUT', name: 'Roustabout' },
  { code: 'CRANE_OPERATOR', name: 'Crane Operator' },
  { code: 'ASSISTANT_CRANE_OPERATOR', name: 'Assistant Crane Operator' },
  { code: 'DECK_PUSHER', name: 'Deck Pusher' },
  { code: 'AB_SEAMAN', name: 'AB Seaman' },
  { code: 'ELECTRICIAN', name: 'Electrician' },
  { code: 'MECHANIC', name: 'Mechanic' },
  { code: 'CHIEF_ELECTRICIAN', name: 'Chief Electrician' },
  { code: 'CHIEF_MECHANIC', name: 'Chief Mechanic' },
  { code: 'ET', name: 'ET' },
  { code: 'BARGE_CAPTAIN', name: 'Barge Captain' },
  { code: 'ASSISTANT_BARGE_CAPTAIN', name: 'Assistant Barge Captain' },
  { code: 'MOTORMAN', name: 'Motorman' },
  { code: 'STC', name: 'STC' },
  { code: 'MEDIC', name: 'Medic' },
  { code: 'CAMPBOSS', name: 'Campboss' },
  { code: 'CHIEF_COOK', name: 'Chief Cook' },
  { code: 'BCO', name: 'BCO' },
  { code: 'SCAFFOLDER', name: 'Scaffolder' },
  { code: 'PAINTER', name: 'Painter' },
  { code: 'WELDER', name: 'Welder' },
  { code: 'THIRD_PARTY', name: 'Third Party' },
  { code: 'ASST_DRILLER', name: 'Asst. Driller' },
  { code: 'HLO', name: 'HLO' },
  { code: 'RADIO_OPERATOR', name: 'Radio Operator' },
  { code: 'STORE_MAN', name: 'Store Man' },
  { code: 'MATERIAL_COORDINATOR', name: 'Material Coordinator' },
] as const;
