import oracledb from 'oracledb';
import { connectionConfig } from './migration-core.js';
const o={outFormat:oracledb.OUT_FORMAT_OBJECT};
async function main(){const c=await oracledb.getConnection(connectionConfig());let jsaId='';try{const next=async(sequence:string)=>{const r=await c.execute<{ID:string}>(`SELECT TO_CHAR(${sequence}.NEXTVAL) ID FROM DUAL`,{},o);return r.rows![0]!.ID;};const actor='phase3-verifier';
  const siteId=await next('SEQ_SYS_SITE'),rigId=await next('SEQ_SYS_RIG'),deptId=await next('SEQ_SYS_DEPARTMENT'),userId=await next('SEQ_SYS_USER');
  await c.execute(`INSERT INTO SYS_SITE(SITE_ID,SITE_CODE,SITE_NAME,SEQUENCE_CODE,TIMEZONE_NAME,CREATED_BY,UPDATED_BY) VALUES(:id,'P3V','Phase 3 Verify','P3SEQ','UTC',:a,:a)`,{id:siteId,a:actor});
  await c.execute(`INSERT INTO SYS_RIG(RIG_ID,SITE_ID,RIG_CODE,RIG_NAME,CREATED_SITE_ID,UPDATED_SITE_ID,CREATED_BY,UPDATED_BY) VALUES(:id,:site,'P3R','Phase 3 Rig',:site,:site,:a,:a)`,{id:rigId,site:siteId,a:actor});
  await c.execute(`INSERT INTO SYS_DEPARTMENT(DEPARTMENT_ID,SITE_ID,RIG_ID,DEPARTMENT_CODE,DEPARTMENT_NAME,CREATED_SITE_ID,UPDATED_SITE_ID,CREATED_BY,UPDATED_BY) VALUES(:id,:site,:rig,'P3D','Phase 3 Department',:site,:site,:a,:a)`,{id:deptId,site:siteId,rig:rigId,a:actor});
  await c.execute(`INSERT INTO SYS_USER(USER_ID,ENTERPRISE_IDENTITY_KEY,USERNAME,DISPLAY_NAME,DEFAULT_SITE_ID,DEFAULT_RIG_ID,DEFAULT_DEPARTMENT_ID,CREATED_SITE_ID,UPDATED_SITE_ID,CREATED_BY,UPDATED_BY) VALUES(:id,'phase3-verifier','phase3-verifier','Phase 3 Verifier',:site,:rig,:dept,:site,:site,:a,:a)`,{id:userId,site:siteId,rig:rigId,dept:deptId,a:actor});
  const jobId=await next('SEQ_SYS_JOB_TYPE'),positionId=await next('SEQ_SYS_POSITION'),categoryId=await next('SEQ_SYS_TOOL_CATEGORY'),toolId=await next('SEQ_SYS_TOOL'),promptId=await next('SEQ_SYS_HAZARD_PROMPT');
  await c.execute(`INSERT INTO SYS_JOB_TYPE(JOB_TYPE_ID,JOB_TYPE_CODE,JOB_TYPE_NAME,SCOPE_TYPE,CREATED_BY,UPDATED_BY) VALUES(:id,'P3JOB','Verify Job','GLOBAL',:a,:a)`,{id:jobId,a:actor});
  await c.execute(`INSERT INTO SYS_POSITION(POSITION_ID,POSITION_CODE,POSITION_NAME,SCOPE_TYPE,CREATED_BY,UPDATED_BY) VALUES(:id,'P3POS','Verify Position','GLOBAL',:a,:a)`,{id:positionId,a:actor});
  await c.execute(`INSERT INTO SYS_TOOL_CATEGORY(TOOL_CATEGORY_ID,CATEGORY_CODE,CATEGORY_NAME,SCOPE_TYPE,CREATED_BY,UPDATED_BY) VALUES(:id,'P3CAT','Verify Category','GLOBAL',:a,:a)`,{id:categoryId,a:actor});
  await c.execute(`INSERT INTO SYS_TOOL(TOOL_ID,TOOL_CATEGORY_ID,TOOL_CODE,TOOL_NAME,SCOPE_TYPE,CREATED_BY,UPDATED_BY) VALUES(:id,:cat,'P3TOOL','Verify Tool','GLOBAL',:a,:a)`,{id:toolId,cat:categoryId,a:actor});
  await c.execute(`INSERT INTO SYS_HAZARD_PROMPT(PROMPT_ID,PROMPT_CODE,PROMPT_LABEL,SCOPE_TYPE,CREATED_BY,UPDATED_BY) VALUES(:id,'P3PROMPT','Verify prompt','GLOBAL',:a,:a)`,{id:promptId,a:actor});
  const matrixId=await next('SEQ_JSA_RISK_MATRIX'),matrixVersionId=await next('SEQ_JSA_RISK_MATRIX_VER');
  await c.execute(`INSERT INTO JSA_RISK_MATRIX(MATRIX_ID,MATRIX_CODE,MATRIX_NAME,DIMENSION_SIZE,CREATED_BY,UPDATED_BY) VALUES(:id,'P3M','Verify Matrix',5,:a,:a)`,{id:matrixId,a:actor});
  await c.execute(`INSERT INTO JSA_RISK_MATRIX_VERSION(MATRIX_VERSION_ID,MATRIX_ID,VERSION_CODE,CREATED_BY,UPDATED_BY) VALUES(:id,:matrix,'V1',:a,:a)`,{id:matrixVersionId,matrix:matrixId,a:actor});
  const likelihoods:string[]=[],severities:string[]=[];for(let i=1;i<=5;i++){const id=await next('SEQ_JSA_RISK_LIKELIHOOD');likelihoods.push(id);await c.execute(`INSERT INTO JSA_RISK_LIKELIHOOD(LIKELIHOOD_ID,MATRIX_VERSION_ID,LIKELIHOOD_CODE,LIKELIHOOD_LABEL,DISPLAY_ORDER,DEFINITION,CREATED_BY,UPDATED_BY) VALUES(:id,:v,:code,:label,:n,'verify',:a,:a)`,{id,v:matrixVersionId,code:String(i),label:`L${i}`,n:i,a:actor});}for(let i=0;i<5;i++){const id=await next('SEQ_JSA_RISK_SEVERITY');severities.push(id);await c.execute(`INSERT INTO JSA_RISK_SEVERITY(SEVERITY_ID,MATRIX_VERSION_ID,SEVERITY_CODE,SEVERITY_LABEL,DISPLAY_ORDER,GENERAL_DEFINITION,CREATED_BY,UPDATED_BY) VALUES(:id,:v,:code,:label,:n,'verify',:a,:a)`,{id,v:matrixVersionId,code:String.fromCharCode(65+i),label:`S${i+1}`,n:i+1,a:actor});}
  const lowId=await next('SEQ_JSA_RISK_RESULT'),extremeId=await next('SEQ_JSA_RISK_RESULT');await c.execute(`INSERT INTO JSA_RISK_RESULT(RISK_RESULT_ID,MATRIX_VERSION_ID,RESULT_CODE,RESULT_NAME,DISPLAY_ORDER,PROHIBITED_FLAG,CREATED_BY,UPDATED_BY) VALUES(:id,:v,'LOW','Low',1,'N',:a,:a)`,{id:lowId,v:matrixVersionId,a:actor});await c.execute(`INSERT INTO JSA_RISK_RESULT(RISK_RESULT_ID,MATRIX_VERSION_ID,RESULT_CODE,RESULT_NAME,DISPLAY_ORDER,PROHIBITED_FLAG,CREATED_BY,UPDATED_BY) VALUES(:id,:v,'EXTREME','Extreme',2,'Y',:a,:a)`,{id:extremeId,v:matrixVersionId,a:actor});let mixedCell='';for(let l=0;l<5;l++)for(let s=0;s<5;s++){const id=await next('SEQ_JSA_RISK_MATRIX_CELL'),mixed=l===4&&s===3;if(mixed)mixedCell=id;await c.execute(`INSERT INTO JSA_RISK_MATRIX_CELL(MATRIX_CELL_ID,MATRIX_VERSION_ID,LIKELIHOOD_ID,SEVERITY_ID,RATING_CODE,RISK_RESULT_ID,CREATED_BY,UPDATED_BY) VALUES(:id,:v,:l,:s,:rating,:result,:a,:a)`,{id,v:matrixVersionId,l:likelihoods[l],s:severities[s],rating:mixed?'E':'L',result:mixed?extremeId:lowId,a:actor});}
  const assignmentId=await next('SEQ_JSA_RIG_MATRIX_ASSIGN');await c.execute(`INSERT INTO JSA_RIG_MATRIX_ASSIGNMENT(RIG_MATRIX_ASSIGNMENT_ID,RIG_ID,MATRIX_VERSION_ID,EFFECTIVE_FROM,REASON_TEXT,CREATED_BY,UPDATED_BY) VALUES(:id,:rig,:v,SYSTIMESTAMP-INTERVAL '1' DAY,'verify',:a,:a)`,{id:assignmentId,rig:rigId,v:matrixVersionId,a:actor});
  jsaId=await next('SEQ_JSA_MASTER');const versionId=await next('SEQ_JSA_VERSION');await c.execute(`INSERT INTO JSA_MASTER(JSA_ID,JSA_NUMBER,NUMBER_SCOPE_KEY,OWNER_SITE_ID,RIG_ID,DEPARTMENT_ID,ORIGIN_SITE_ID,CREATED_SITE_ID,UPDATED_SITE_ID,CREATOR_USER_ID,CREATED_BY,UPDATED_BY) VALUES(:id,'VERIFY-1','GLOBAL',:site,:rig,:dept,:site,:site,:site,:userId,:a,:a)`,{id:jsaId,site:siteId,rig:rigId,dept:deptId,userId,a:actor});await c.execute(`INSERT INTO JSA_VERSION(JSA_VERSION_ID,JSA_ID,VERSION_NUMBER,OWNER_SITE_ID,RIG_ID,DEPARTMENT_ID,JOB_TYPE_ID,MATRIX_VERSION_ID,JOB_TITLE,CREATED_BY,UPDATED_BY) VALUES(:id,:jsa,1,:site,:rig,:dept,:job,:matrix,'Verify draft',:a,:a)`,{id:versionId,jsa:jsaId,site:siteId,rig:rigId,dept:deptId,job:jobId,matrix:matrixVersionId,a:actor});await c.execute(`UPDATE JSA_MASTER SET WORKING_VERSION_ID=:v WHERE JSA_ID=:id`,{v:versionId,id:jsaId});
  const taskId=await next('SEQ_JSA_VER_TASK'),hazardId=await next('SEQ_JSA_VER_HAZARD'),controlId=await next('SEQ_JSA_VER_CONTROL');await c.execute(`INSERT INTO JSA_VERSION_TASK(VERSION_TASK_ID,JSA_VERSION_ID,LOGICAL_KEY,TASK_TITLE,CREATED_BY,UPDATED_BY) VALUES(:id,:v,:id,'Verify task',:a,:a)`,{id:taskId,v:versionId,a:actor});await c.execute(`INSERT INTO JSA_VERSION_HAZARD(VERSION_HAZARD_ID,JSA_VERSION_ID,LOGICAL_KEY,VERSION_TASK_ID,HAZARD_TEXT,INITIAL_LIKELIHOOD_ID,INITIAL_SEVERITY_ID,INITIAL_CELL_ID,INITIAL_RATING_CODE,INITIAL_RESULT_CODE,INITIAL_RESULT_NAME,INITIAL_PROHIBITED_FLAG,RESIDUAL_LIKELIHOOD_ID,RESIDUAL_SEVERITY_ID,RESIDUAL_CELL_ID,RESIDUAL_RATING_CODE,RESIDUAL_RESULT_CODE,RESIDUAL_RESULT_NAME,RESIDUAL_PROHIBITED_FLAG,CREATED_BY,UPDATED_BY) VALUES(:id,:v,:id,:task,'Verify hazard',:l,:s,:cell,'E','EXTREME','Extreme','Y',:l,:s,:cell,'E','EXTREME','Extreme','Y',:a,:a)`,{id:hazardId,v:versionId,task:taskId,l:likelihoods[4],s:severities[3],cell:mixedCell,a:actor});await c.execute(`INSERT INTO JSA_VERSION_CONTROL(VERSION_CONTROL_ID,JSA_VERSION_ID,VERSION_HAZARD_ID,LOGICAL_KEY,CONTROL_TEXT,CREATED_BY,UPDATED_BY) VALUES(:id,:v,:haz,:id,'Verify control',:a,:a)`,{id:controlId,v:versionId,haz:hazardId,a:actor});
  const check=await c.execute<{RATING_CODE:string;RESULT_CODE:string;WORKING_VERSION_ID:string}>(`SELECT H.RESIDUAL_RATING_CODE RATING_CODE,H.RESIDUAL_RESULT_CODE RESULT_CODE,TO_CHAR(M.WORKING_VERSION_ID) WORKING_VERSION_ID FROM JSA_VERSION_HAZARD H JOIN JSA_VERSION V ON V.JSA_VERSION_ID=H.JSA_VERSION_ID JOIN JSA_MASTER M ON M.JSA_ID=V.JSA_ID WHERE H.VERSION_HAZARD_ID=:id`,{id:hazardId},o);if(check.rows?.[0]?.RATING_CODE!=='E'||check.rows[0].RESULT_CODE!=='EXTREME'||check.rows[0].WORKING_VERSION_ID!==versionId)throw new Error('Draft snapshot or working pointer verification failed');
  await c.execute(`UPDATE JSA_VERSION SET VERSION_STATUS='CANCELLED' WHERE JSA_VERSION_ID=:id`,{id:versionId});await c.execute(`UPDATE JSA_MASTER SET LIFECYCLE_STATUS='CANCELLED',WORKING_VERSION_ID=NULL WHERE JSA_ID=:id`,{id:jsaId});const cancelled=await c.execute<{STATUS:string;WORKING_COUNT:number;CURRENT_COUNT:number}>(`SELECT LIFECYCLE_STATUS STATUS,COUNT(WORKING_VERSION_ID) WORKING_COUNT,COUNT(CURRENT_VERSION_ID) CURRENT_COUNT FROM JSA_MASTER WHERE JSA_ID=:id GROUP BY LIFECYCLE_STATUS`,{id:jsaId},o);if(cancelled.rows?.[0]?.STATUS!=='CANCELLED'||cancelled.rows[0].WORKING_COUNT!==0||cancelled.rows[0].CURRENT_COUNT!==0)throw new Error('Cancellation pointer semantics failed');await c.rollback();const gone=await c.execute<{C:number}>(`SELECT COUNT(*) C FROM JSA_MASTER WHERE JSA_ID=:id`,{id:jsaId},o);if(gone.rows?.[0]?.C!==0)throw new Error('Behavior transaction did not roll back');console.log(JSON.stringify({status:'PASS',transactionRolledBack:true,checks:['atomic master/version pointers','stable logical keys','same-version task/hazard/control','5/D resolves to E/EXTREME snapshots','residual prohibited snapshot','cancel clears only working pointer']}));}catch(error){await c.rollback();throw error;}finally{await c.close();}}
main().catch(error=>{console.error(JSON.stringify({status:'FAIL',message:error instanceof Error?error.message:String(error),oracleErrorCode:(error as {errorNum?:number}).errorNum}));process.exitCode=1;});
