DECLARE
  V_WITHOUT_JOB_TYPE NUMBER;
BEGIN
  SELECT COUNT(*)
  INTO V_WITHOUT_JOB_TYPE
  FROM JSA_VERSION
  WHERE JOB_TYPE_ID IS NULL;

  IF V_WITHOUT_JOB_TYPE>0 THEN
    RAISE_APPLICATION_ERROR(
      -20067,
      'Cannot restore mandatory Job Type while JSA Versions without Job Type exist'
    );
  END IF;
END;
/

DROP TRIGGER TRG_JSA_VERSION_ENGLISH;
ALTER TABLE JSA_VERSION MODIFY (LANGUAGE_ID NULL);
ALTER TABLE JSA_VERSION MODIFY (JOB_TYPE_ID NOT NULL);
