DROP TRIGGER TRG_JSA_OFFICIAL_NUM_IMMUTABLE;
DROP TABLE JSA_NUMBER_COUNTER CASCADE CONSTRAINTS;
ALTER TABLE JSA_MASTER DROP CONSTRAINT CHK_JSA_MASTER_NUM_STATUS;
ALTER TABLE JSA_MASTER DROP COLUMN NUMBER_STATUS;
