DELETE FROM SYS_ROLE_PERMISSION
WHERE PERMISSION_ID IN (
  SELECT PERMISSION_ID FROM SYS_PERMISSION WHERE PERMISSION_CODE='ATTACHMENT_LIBRARY_ADMIN'
)
AND CREATED_BY='MIGRATION_012';

DELETE FROM SYS_PERMISSION
WHERE PERMISSION_CODE='ATTACHMENT_LIBRARY_ADMIN' AND CREATED_BY='MIGRATION_012';

DROP INDEX IX_JSA_VER_ATTACH_LIBRARY;
ALTER TABLE JSA_VERSION_ATTACHMENT DROP CONSTRAINT FK_JSA_VER_ATTACH_LIBRARY;
ALTER TABLE JSA_VERSION_ATTACHMENT DROP COLUMN CONTENT_SHA256;
ALTER TABLE JSA_VERSION_ATTACHMENT DROP COLUMN LIBRARY_ASSET_VERSION_ID;

ALTER TABLE JSA_ATTACHMENT_ASSET DROP CONSTRAINT FK_JSA_ATTACH_ASSET_CURRENT;
DROP TABLE JSA_ATTACHMENT_ASSET_VERSION CASCADE CONSTRAINTS;
DROP TABLE JSA_ATTACHMENT_ASSET CASCADE CONSTRAINTS;
DROP TABLE JSA_ATTACHMENT_FOLDER CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_JSA_ATTACHMENT_VERSION;
DROP SEQUENCE SEQ_JSA_ATTACHMENT_ASSET;
DROP SEQUENCE SEQ_JSA_ATTACHMENT_FOLDER;
