CREATE OR REPLACE PROCEDURE JSA_ASSERT_VERSION_MUTABLE(P_VERSION_ID NUMBER) AS
  V_STATUS JSA_VERSION.VERSION_STATUS%TYPE;
BEGIN
  SELECT VERSION_STATUS INTO V_STATUS FROM JSA_VERSION WHERE JSA_VERSION_ID=P_VERSION_ID;
  IF V_STATUS='PUBLISHED' THEN
    RAISE_APPLICATION_ERROR(-20041,'Published JSA Version is immutable');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_JSA_VER_IMMUTABLE BEFORE UPDATE OR DELETE ON JSA_VERSION FOR EACH ROW
BEGIN
  IF :OLD.VERSION_STATUS='PUBLISHED' THEN
    RAISE_APPLICATION_ERROR(-20041,'Published JSA Version is immutable');
  END IF;
END;
/

ALTER TRIGGER TRG_JSA_PROMPT_IMMUTABLE COMPILE;
ALTER TRIGGER TRG_JSA_COVER_IMMUTABLE COMPILE;
ALTER TRIGGER TRG_JSA_TASK_IMMUTABLE COMPILE;
ALTER TRIGGER TRG_JSA_HAZARD_IMMUTABLE COMPILE;
ALTER TRIGGER TRG_JSA_CONTROL_IMUTABLE COMPILE;
ALTER TRIGGER TRG_JSA_STEP_IMMUTABLE COMPILE;
ALTER TRIGGER TRG_JSA_PERF_IMMUTABLE COMPILE;
ALTER TRIGGER TRG_JSA_SUP_IMMUTABLE COMPILE;
ALTER TRIGGER TRG_JSA_TOOL_IMMUTABLE COMPILE;
ALTER TRIGGER TRG_JSA_PROC_IMMUTABLE COMPILE;
ALTER TRIGGER TRG_JSA_ATTACH_IMMUTABLE COMPILE;
/

DECLARE
  V_SUPERSEDED NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_SUPERSEDED FROM JSA_VERSION WHERE VERSION_STATUS='SUPERSEDED';
  IF V_SUPERSEDED>0 THEN
    RAISE_APPLICATION_ERROR(-20090,'Cannot roll back Phase 5 while Superseded versions exist');
  END IF;
END;
/

ALTER TABLE JSA_VERSION DROP CONSTRAINT CHK_JSA_VER_PUBLISHED;
ALTER TABLE JSA_VERSION DROP CONSTRAINT CHK_JSA_VERSION_STATUS;
ALTER TABLE JSA_VERSION ADD CONSTRAINT CHK_JSA_VERSION_STATUS CHECK (
  VERSION_STATUS IN ('DRAFT','DEPARTMENT_HEAD_REVIEW','STC_REVIEW','OIM_REVIEW',
    'RIG_MANAGER_REVIEW','RETURNED','REJECTED','PUBLISHED','CANCELLED')
);
ALTER TABLE JSA_VERSION ADD CONSTRAINT CHK_JSA_VER_PUBLISHED CHECK (
  (VERSION_STATUS='PUBLISHED' AND PUBLISHED_AT IS NOT NULL
    AND PUBLISHED_BY_USER_ID IS NOT NULL AND PUBLISHED_BY_USERNAME IS NOT NULL)
  OR
  (VERSION_STATUS<>'PUBLISHED' AND PUBLISHED_AT IS NULL
    AND PUBLISHED_BY_USER_ID IS NULL AND PUBLISHED_BY_USERNAME IS NULL)
);

DROP INDEX IX_JSA_VERSION_BASE;
DROP INDEX IX_JSA_MASTER_CURRENT_WORKING;
ALTER TABLE JSA_MASTER DROP CONSTRAINT CHK_JSA_MASTER_CHECKOUT;
ALTER TABLE JSA_MASTER DROP CONSTRAINT FK_JSA_MASTER_CHECKOUT_USER;
ALTER TABLE JSA_MASTER DROP COLUMN CHECKED_OUT_AT;
ALTER TABLE JSA_MASTER DROP COLUMN CHECKED_OUT_BY_DISPLAY_NAME;
ALTER TABLE JSA_MASTER DROP COLUMN CHECKED_OUT_BY_USERNAME;
ALTER TABLE JSA_MASTER DROP COLUMN CHECKED_OUT_BY_USER_ID;
