CREATE OR REPLACE TRIGGER TRG_JSA_VER_IMMUTABLE
BEFORE UPDATE OR DELETE ON JSA_VERSION
FOR EACH ROW
BEGIN
  IF DELETING AND :OLD.VERSION_STATUS IN ('PUBLISHED','SUPERSEDED') THEN
    RAISE_APPLICATION_ERROR(-20041,'Published or Superseded JSA Version is immutable');
  END IF;

  IF UPDATING AND :OLD.VERSION_STATUS='SUPERSEDED' THEN
    RAISE_APPLICATION_ERROR(-20041,'Superseded JSA Version is immutable');
  END IF;

  IF UPDATING AND :OLD.VERSION_STATUS='PUBLISHED' THEN
    IF :NEW.VERSION_STATUS<>'SUPERSEDED'
       OR :NEW.JSA_ID<>:OLD.JSA_ID
       OR :NEW.VERSION_NUMBER<>:OLD.VERSION_NUMBER
       OR NVL(:NEW.VERSION_LABEL,CHR(0))<>NVL(:OLD.VERSION_LABEL,CHR(0))
       OR NVL(:NEW.BASE_VERSION_ID,-1)<>NVL(:OLD.BASE_VERSION_ID,-1)
       OR :NEW.OWNER_SITE_ID<>:OLD.OWNER_SITE_ID
       OR :NEW.RIG_ID<>:OLD.RIG_ID
       OR :NEW.DEPARTMENT_ID<>:OLD.DEPARTMENT_ID
       OR NVL(:NEW.JOB_TYPE_ID,-1)<>NVL(:OLD.JOB_TYPE_ID,-1)
       OR :NEW.MATRIX_VERSION_ID<>:OLD.MATRIX_VERSION_ID
       OR :NEW.LANGUAGE_ID<>:OLD.LANGUAGE_ID
       OR NVL(:NEW.JOB_TITLE,CHR(0))<>NVL(:OLD.JOB_TITLE,CHR(0))
       OR (:NEW.JOB_DESCRIPTION IS NULL AND :OLD.JOB_DESCRIPTION IS NOT NULL)
       OR (:NEW.JOB_DESCRIPTION IS NOT NULL AND :OLD.JOB_DESCRIPTION IS NULL)
       OR (:NEW.JOB_DESCRIPTION IS NOT NULL AND :OLD.JOB_DESCRIPTION IS NOT NULL
           AND DBMS_LOB.COMPARE(:NEW.JOB_DESCRIPTION,:OLD.JOB_DESCRIPTION)<>0)
       OR NVL(:NEW.LOCATION_TEXT,CHR(0))<>NVL(:OLD.LOCATION_TEXT,CHR(0))
       OR NVL(:NEW.PERSONNEL_TEXT,CHR(0))<>NVL(:OLD.PERSONNEL_TEXT,CHR(0))
       OR :NEW.PTW_REQUIRED_FLAG<>:OLD.PTW_REQUIRED_FLAG
       OR NVL(:NEW.PTW_REFERENCE,CHR(0))<>NVL(:OLD.PTW_REFERENCE,CHR(0))
       OR :NEW.PUBLISHED_AT<>:OLD.PUBLISHED_AT
       OR :NEW.PUBLISHED_BY_USER_ID<>:OLD.PUBLISHED_BY_USER_ID
       OR :NEW.PUBLISHED_BY_USERNAME<>:OLD.PUBLISHED_BY_USERNAME
    THEN
      RAISE_APPLICATION_ERROR(-20041,'Published JSA Version is immutable except for superseding');
    END IF;
  END IF;
END;
/

ALTER TRIGGER TRG_JSA_PROMPT_IMMUTABLE COMPILE;
ALTER TRIGGER TRG_JSA_COVER_IMMUTABLE COMPILE;
ALTER TRIGGER TRG_JSA_TASK_IMMUTABLE COMPILE;
ALTER TRIGGER TRG_JSA_HAZARD_IMMUTABLE COMPILE;
ALTER TRIGGER TRG_JSA_CONTROL_IMUTABLE COMPILE;
ALTER TRIGGER TRG_JSA_STEP_IMMUTABLE COMPILE;
ALTER TRIGGER TRG_JSA_PERF_IMMUTABLE COMPILE;
ALTER TRIGGER TRG_JSA_SUP_IMMUTABLE COMPILE;
ALTER TRIGGER TRG_JSA_TOOL_IMMUTABLE COMPILE;
ALTER TRIGGER TRG_JSA_PROC_IMMUTABLE COMPILE;
ALTER TRIGGER TRG_JSA_ATTACH_IMMUTABLE COMPILE;
