DROP INDEX IX_JSA_VERSION_BROWSE_ACTORS;
DROP INDEX IX_JSA_VERSION_BROWSE_STATE;
DELETE FROM SYS_SITE_SEQUENCE_RANGE
WHERE SEQUENCE_CODE='SEQ_JSA_USER_FAVORITE';
DROP TABLE JSA_USER_FAVORITE CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_JSA_USER_FAVORITE;
