DECLARE
  V_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM JSA_COPY_PROVENANCE;
  IF V_COUNT > 0 THEN
    RAISE_APPLICATION_ERROR(
      -20072,
      'Rollback 017 refused: JSA copy provenance rows exist; remediate controlled non-production fixtures first'
    );
  END IF;
END;
/

DROP TRIGGER TRG_JSA_COPY_PROV_IMMUTABLE;
DROP INDEX IX_JSA_COPY_TIME;
DROP INDEX IX_JSA_COPY_SOURCE;
DELETE FROM SYS_SITE_SEQUENCE_RANGE
WHERE SEQUENCE_CODE='SEQ_JSA_COPY_PROVENANCE';
DROP TABLE JSA_COPY_PROVENANCE CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_JSA_COPY_PROVENANCE;
