CREATE OR REPLACE TRIGGER TRG_JSA_OFFICIAL_NUM_IMMUTABLE
BEFORE UPDATE OF JSA_NUMBER,NUMBER_SCOPE_KEY,NUMBER_STATUS ON JSA_MASTER
FOR EACH ROW
BEGIN
  IF :OLD.NUMBER_STATUS='OFFICIAL'
     AND (
       :NEW.JSA_NUMBER<>:OLD.JSA_NUMBER
       OR :NEW.NUMBER_SCOPE_KEY<>:OLD.NUMBER_SCOPE_KEY
       OR :NEW.NUMBER_STATUS<>:OLD.NUMBER_STATUS
     )
  THEN
    RAISE_APPLICATION_ERROR(-20068,'Official JSA number is immutable');
  END IF;
END;
/
