CREATE TABLE JSA_SCHEMA_VERSION (
    MIGRATION_ID       VARCHAR2(50)    NOT NULL,
    MIGRATION_NAME     VARCHAR2(200)   NOT NULL,
    CHECKSUM_VALUE     VARCHAR2(64)    NOT NULL,
    APPLIED_AT         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    APPLIED_BY         VARCHAR2(100)   NOT NULL,
    EXECUTION_MS       NUMBER(10),
    STATUS_CODE        VARCHAR2(20)    NOT NULL,
    CONSTRAINT PK_JSA_SCHEMA_VERSION PRIMARY KEY (MIGRATION_ID),
    CONSTRAINT CHK_JSA_SCHEMA_VER_STATUS CHECK (STATUS_CODE IN ('APPLIED', 'FAILED', 'ROLLED_BACK'))
)
