CREATE SEQUENCE SEQ_SYS_SITE START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_SYS_RIG START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_SYS_DEPARTMENT START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_SYS_SITE_SEQ_RANGE START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_SYS_USER START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_SYS_ROLE START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_SYS_PERMISSION START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_SYS_USER_ROLE START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_SYS_ROLE_PERMISSION START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_SYS_USER_PERM_OVERRIDE START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_SYS_USER_DATA_SCOPE START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;

CREATE TABLE SYS_SITE (
    SITE_ID          NUMBER(19) NOT NULL,
    SITE_CODE        VARCHAR2(50 CHAR) NOT NULL,
    SITE_NAME        VARCHAR2(200 CHAR) NOT NULL,
    SEQUENCE_CODE    VARCHAR2(50 CHAR) NOT NULL,
    TIMEZONE_NAME    VARCHAR2(100 CHAR) NOT NULL,
    IS_ACTIVE        CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(255 CHAR) NOT NULL,
    UPDATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY       VARCHAR2(255 CHAR) NOT NULL,
    ROW_VERSION      NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_SYS_SITE PRIMARY KEY (SITE_ID),
    CONSTRAINT UK_SYS_SITE_CODE UNIQUE (SITE_CODE),
    CONSTRAINT UK_SYS_SITE_SEQ_CODE UNIQUE (SEQUENCE_CODE),
    CONSTRAINT CHK_SYS_SITE_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N')),
    CONSTRAINT CHK_SYS_SITE_ROW_VER CHECK (ROW_VERSION >= 1)
);

CREATE TABLE SYS_RIG (
    RIG_ID           NUMBER(19) NOT NULL,
    SITE_ID          NUMBER(19) NOT NULL,
    RIG_CODE         VARCHAR2(50 CHAR) NOT NULL,
    RIG_NAME         VARCHAR2(200 CHAR) NOT NULL,
    IS_ACTIVE        CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CREATED_SITE_ID  NUMBER(19) NOT NULL,
    UPDATED_SITE_ID  NUMBER(19) NOT NULL,
    CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(255 CHAR) NOT NULL,
    UPDATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY       VARCHAR2(255 CHAR) NOT NULL,
    ROW_VERSION      NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_SYS_RIG PRIMARY KEY (RIG_ID),
    CONSTRAINT UK_SYS_RIG_SITE_CODE UNIQUE (SITE_ID, RIG_CODE),
    CONSTRAINT UK_SYS_RIG_ID_SITE UNIQUE (RIG_ID, SITE_ID),
    CONSTRAINT FK_SYS_RIG_SITE FOREIGN KEY (SITE_ID) REFERENCES SYS_SITE (SITE_ID),
    CONSTRAINT FK_SYS_RIG_CREATED_SITE FOREIGN KEY (CREATED_SITE_ID) REFERENCES SYS_SITE (SITE_ID),
    CONSTRAINT FK_SYS_RIG_UPDATED_SITE FOREIGN KEY (UPDATED_SITE_ID) REFERENCES SYS_SITE (SITE_ID),
    CONSTRAINT CHK_SYS_RIG_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N')),
    CONSTRAINT CHK_SYS_RIG_ROW_VER CHECK (ROW_VERSION >= 1)
);

CREATE TABLE SYS_DEPARTMENT (
    DEPARTMENT_ID    NUMBER(19) NOT NULL,
    SITE_ID          NUMBER(19) NOT NULL,
    RIG_ID           NUMBER(19),
    DEPARTMENT_CODE  VARCHAR2(50 CHAR) NOT NULL,
    DEPARTMENT_NAME  VARCHAR2(200 CHAR) NOT NULL,
    IS_ACTIVE        CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CREATED_SITE_ID  NUMBER(19) NOT NULL,
    UPDATED_SITE_ID  NUMBER(19) NOT NULL,
    CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(255 CHAR) NOT NULL,
    UPDATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY       VARCHAR2(255 CHAR) NOT NULL,
    ROW_VERSION      NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_SYS_DEPARTMENT PRIMARY KEY (DEPARTMENT_ID),
    CONSTRAINT UK_SYS_DEPT_SITE_CODE UNIQUE (SITE_ID, DEPARTMENT_CODE),
    CONSTRAINT UK_SYS_DEPT_ID_SITE UNIQUE (DEPARTMENT_ID, SITE_ID),
    CONSTRAINT UK_SYS_DEPT_ID_RIG UNIQUE (DEPARTMENT_ID, RIG_ID),
    CONSTRAINT FK_SYS_DEPT_SITE FOREIGN KEY (SITE_ID) REFERENCES SYS_SITE (SITE_ID),
    CONSTRAINT FK_SYS_DEPT_RIG_SITE FOREIGN KEY (RIG_ID, SITE_ID) REFERENCES SYS_RIG (RIG_ID, SITE_ID),
    CONSTRAINT FK_SYS_DEPT_CREATED_SITE FOREIGN KEY (CREATED_SITE_ID) REFERENCES SYS_SITE (SITE_ID),
    CONSTRAINT FK_SYS_DEPT_UPDATED_SITE FOREIGN KEY (UPDATED_SITE_ID) REFERENCES SYS_SITE (SITE_ID),
    CONSTRAINT CHK_SYS_DEPT_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N')),
    CONSTRAINT CHK_SYS_DEPT_ROW_VER CHECK (ROW_VERSION >= 1)
);

CREATE TABLE SYS_SITE_SEQUENCE_RANGE (
    RANGE_ID         NUMBER(19) NOT NULL,
    SITE_ID          NUMBER(19) NOT NULL,
    SEQUENCE_CODE    VARCHAR2(50 CHAR) NOT NULL,
    RANGE_START      NUMBER(19) NOT NULL,
    RANGE_END        NUMBER(19) NOT NULL,
    EFFECTIVE_FROM   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EFFECTIVE_TO     TIMESTAMP(6),
    IS_ACTIVE        CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(255 CHAR) NOT NULL,
    UPDATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY       VARCHAR2(255 CHAR) NOT NULL,
    ROW_VERSION      NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_SYS_SITE_SEQ_RANGE PRIMARY KEY (RANGE_ID),
    CONSTRAINT UK_SYS_SITE_SEQ_RANGE UNIQUE (SITE_ID, SEQUENCE_CODE),
    CONSTRAINT FK_SYS_SEQ_RANGE_SITE FOREIGN KEY (SITE_ID) REFERENCES SYS_SITE (SITE_ID),
    CONSTRAINT CHK_SYS_SEQ_RANGE_BOUNDS CHECK (RANGE_START <= RANGE_END),
    CONSTRAINT CHK_SYS_SEQ_RANGE_DATES CHECK (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO >= EFFECTIVE_FROM),
    CONSTRAINT CHK_SYS_SEQ_RANGE_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N')),
    CONSTRAINT CHK_SYS_SEQ_RANGE_ROW_VER CHECK (ROW_VERSION >= 1)
);

CREATE TABLE SYS_USER (
    USER_ID               NUMBER(19) NOT NULL,
    ENTERPRISE_IDENTITY_KEY VARCHAR2(255 CHAR) NOT NULL,
    USERNAME              VARCHAR2(255 CHAR) NOT NULL,
    DISPLAY_NAME          VARCHAR2(255 CHAR) NOT NULL,
    EMAIL                 VARCHAR2(320 CHAR),
    DEFAULT_SITE_ID       NUMBER(19),
    DEFAULT_RIG_ID        NUMBER(19),
    DEFAULT_DEPARTMENT_ID NUMBER(19),
    IS_ACTIVE             CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CREATED_SITE_ID       NUMBER(19) NOT NULL,
    UPDATED_SITE_ID       NUMBER(19) NOT NULL,
    CREATED_AT            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY            VARCHAR2(255 CHAR) NOT NULL,
    UPDATED_AT            TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY            VARCHAR2(255 CHAR) NOT NULL,
    ROW_VERSION           NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_SYS_USER PRIMARY KEY (USER_ID),
    CONSTRAINT UK_SYS_USER_IDENTITY UNIQUE (ENTERPRISE_IDENTITY_KEY),
    CONSTRAINT UK_SYS_USER_USERNAME UNIQUE (USERNAME),
    CONSTRAINT FK_SYS_USER_DEFAULT_SITE FOREIGN KEY (DEFAULT_SITE_ID) REFERENCES SYS_SITE (SITE_ID),
    CONSTRAINT FK_SYS_USER_DEFAULT_RIG FOREIGN KEY (DEFAULT_RIG_ID, DEFAULT_SITE_ID) REFERENCES SYS_RIG (RIG_ID, SITE_ID),
    CONSTRAINT FK_SYS_USER_DEFAULT_DEPT FOREIGN KEY (DEFAULT_DEPARTMENT_ID, DEFAULT_SITE_ID) REFERENCES SYS_DEPARTMENT (DEPARTMENT_ID, SITE_ID),
    CONSTRAINT FK_SYS_USER_CREATED_SITE FOREIGN KEY (CREATED_SITE_ID) REFERENCES SYS_SITE (SITE_ID),
    CONSTRAINT FK_SYS_USER_UPDATED_SITE FOREIGN KEY (UPDATED_SITE_ID) REFERENCES SYS_SITE (SITE_ID),
    CONSTRAINT CHK_SYS_USER_DEFAULT_RIG CHECK (DEFAULT_RIG_ID IS NULL OR DEFAULT_SITE_ID IS NOT NULL),
    CONSTRAINT CHK_SYS_USER_DEFAULT_DEPT CHECK (DEFAULT_DEPARTMENT_ID IS NULL OR DEFAULT_SITE_ID IS NOT NULL),
    CONSTRAINT CHK_SYS_USER_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N')),
    CONSTRAINT CHK_SYS_USER_ROW_VER CHECK (ROW_VERSION >= 1)
);

CREATE TABLE SYS_ROLE (
    ROLE_ID           NUMBER(19) NOT NULL,
    ROLE_CODE         VARCHAR2(100 CHAR) NOT NULL,
    ROLE_NAME         VARCHAR2(200 CHAR) NOT NULL,
    DESCRIPTION       VARCHAR2(1000 CHAR),
    IS_SYSTEM_MANAGED CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    IS_ACTIVE         CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CREATED_AT        TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY        VARCHAR2(255 CHAR) NOT NULL,
    UPDATED_AT        TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY        VARCHAR2(255 CHAR) NOT NULL,
    ROW_VERSION       NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_SYS_ROLE PRIMARY KEY (ROLE_ID),
    CONSTRAINT UK_SYS_ROLE_CODE UNIQUE (ROLE_CODE),
    CONSTRAINT CHK_SYS_ROLE_SYSTEM CHECK (IS_SYSTEM_MANAGED IN ('Y', 'N')),
    CONSTRAINT CHK_SYS_ROLE_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N')),
    CONSTRAINT CHK_SYS_ROLE_ROW_VER CHECK (ROW_VERSION >= 1)
);

CREATE TABLE SYS_PERMISSION (
    PERMISSION_ID    NUMBER(19) NOT NULL,
    PERMISSION_CODE  VARCHAR2(150 CHAR) NOT NULL,
    PERMISSION_NAME  VARCHAR2(200 CHAR) NOT NULL,
    DESCRIPTION      VARCHAR2(1000 CHAR),
    PERMISSION_GROUP VARCHAR2(100 CHAR) NOT NULL,
    IS_ACTIVE        CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(255 CHAR) NOT NULL,
    UPDATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY       VARCHAR2(255 CHAR) NOT NULL,
    ROW_VERSION      NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_SYS_PERMISSION PRIMARY KEY (PERMISSION_ID),
    CONSTRAINT UK_SYS_PERMISSION_CODE UNIQUE (PERMISSION_CODE),
    CONSTRAINT CHK_SYS_PERMISSION_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N')),
    CONSTRAINT CHK_SYS_PERMISSION_ROW_VER CHECK (ROW_VERSION >= 1)
);

CREATE TABLE SYS_USER_ROLE (
    USER_ROLE_ID     NUMBER(19) NOT NULL,
    USER_ID          NUMBER(19) NOT NULL,
    ROLE_ID          NUMBER(19) NOT NULL,
    IS_ACTIVE        CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    ASSIGNED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    REVOKED_AT       TIMESTAMP(6),
    CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(255 CHAR) NOT NULL,
    UPDATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY       VARCHAR2(255 CHAR) NOT NULL,
    ROW_VERSION      NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_SYS_USER_ROLE PRIMARY KEY (USER_ROLE_ID),
    CONSTRAINT FK_SYS_USER_ROLE_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USER (USER_ID),
    CONSTRAINT FK_SYS_USER_ROLE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES SYS_ROLE (ROLE_ID),
    CONSTRAINT CHK_SYS_USER_ROLE_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N')),
    CONSTRAINT CHK_SYS_USER_ROLE_REVOKED CHECK ((IS_ACTIVE = 'Y' AND REVOKED_AT IS NULL) OR IS_ACTIVE = 'N'),
    CONSTRAINT CHK_SYS_USER_ROLE_ROW_VER CHECK (ROW_VERSION >= 1)
);

CREATE TABLE SYS_ROLE_PERMISSION (
    ROLE_PERMISSION_ID NUMBER(19) NOT NULL,
    ROLE_ID             NUMBER(19) NOT NULL,
    PERMISSION_ID       NUMBER(19) NOT NULL,
    IS_ACTIVE           CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    ASSIGNED_AT         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    REVOKED_AT          TIMESTAMP(6),
    CREATED_AT          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY          VARCHAR2(255 CHAR) NOT NULL,
    UPDATED_AT          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY          VARCHAR2(255 CHAR) NOT NULL,
    ROW_VERSION         NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_SYS_ROLE_PERMISSION PRIMARY KEY (ROLE_PERMISSION_ID),
    CONSTRAINT FK_SYS_ROLE_PERM_ROLE FOREIGN KEY (ROLE_ID) REFERENCES SYS_ROLE (ROLE_ID),
    CONSTRAINT FK_SYS_ROLE_PERM_PERM FOREIGN KEY (PERMISSION_ID) REFERENCES SYS_PERMISSION (PERMISSION_ID),
    CONSTRAINT CHK_SYS_ROLE_PERM_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N')),
    CONSTRAINT CHK_SYS_ROLE_PERM_REVOKED CHECK ((IS_ACTIVE = 'Y' AND REVOKED_AT IS NULL) OR IS_ACTIVE = 'N'),
    CONSTRAINT CHK_SYS_ROLE_PERM_ROW_VER CHECK (ROW_VERSION >= 1)
);

CREATE TABLE SYS_USER_PERMISSION_OVERRIDE (
    USER_PERMISSION_OVERRIDE_ID NUMBER(19) NOT NULL,
    USER_ID          NUMBER(19) NOT NULL,
    PERMISSION_ID    NUMBER(19) NOT NULL,
    EFFECT_CODE      VARCHAR2(10 CHAR) NOT NULL,
    REASON_TEXT      VARCHAR2(1000 CHAR),
    IS_ACTIVE        CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    EFFECTIVE_FROM   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EFFECTIVE_TO     TIMESTAMP(6),
    CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(255 CHAR) NOT NULL,
    UPDATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY       VARCHAR2(255 CHAR) NOT NULL,
    ROW_VERSION      NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_SYS_USER_PERM_OVERRIDE PRIMARY KEY (USER_PERMISSION_OVERRIDE_ID),
    CONSTRAINT FK_SYS_USER_PERM_OVR_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USER (USER_ID),
    CONSTRAINT FK_SYS_USER_PERM_OVR_PERM FOREIGN KEY (PERMISSION_ID) REFERENCES SYS_PERMISSION (PERMISSION_ID),
    CONSTRAINT CHK_SYS_USER_PERM_OVR_EFFECT CHECK (EFFECT_CODE IN ('ALLOW', 'DENY')),
    CONSTRAINT CHK_SYS_USER_PERM_OVR_DATES CHECK (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO >= EFFECTIVE_FROM),
    CONSTRAINT CHK_SYS_USER_PERM_OVR_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N')),
    CONSTRAINT CHK_SYS_USER_PERM_OVR_ROW_VER CHECK (ROW_VERSION >= 1)
);

CREATE TABLE SYS_USER_DATA_SCOPE (
    USER_DATA_SCOPE_ID NUMBER(19) NOT NULL,
    USER_ID          NUMBER(19) NOT NULL,
    SCOPE_TYPE       VARCHAR2(20 CHAR) NOT NULL,
    SITE_ID          NUMBER(19) NOT NULL,
    RIG_ID           NUMBER(19),
    DEPARTMENT_ID    NUMBER(19),
    CAN_VIEW         CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CAN_ACT          CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    IS_ACTIVE        CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    EFFECTIVE_FROM   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    EFFECTIVE_TO     TIMESTAMP(6),
    CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY       VARCHAR2(255 CHAR) NOT NULL,
    UPDATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_BY       VARCHAR2(255 CHAR) NOT NULL,
    ROW_VERSION      NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_SYS_USER_DATA_SCOPE PRIMARY KEY (USER_DATA_SCOPE_ID),
    CONSTRAINT FK_SYS_USER_SCOPE_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USER (USER_ID),
    CONSTRAINT FK_SYS_USER_SCOPE_SITE FOREIGN KEY (SITE_ID) REFERENCES SYS_SITE (SITE_ID),
    CONSTRAINT FK_SYS_USER_SCOPE_RIG FOREIGN KEY (RIG_ID, SITE_ID) REFERENCES SYS_RIG (RIG_ID, SITE_ID),
    CONSTRAINT FK_SYS_USER_SCOPE_DEPT FOREIGN KEY (DEPARTMENT_ID, SITE_ID) REFERENCES SYS_DEPARTMENT (DEPARTMENT_ID, SITE_ID),
    CONSTRAINT FK_SYS_USER_SCOPE_DEPT_RIG FOREIGN KEY (DEPARTMENT_ID, RIG_ID) REFERENCES SYS_DEPARTMENT (DEPARTMENT_ID, RIG_ID),
    CONSTRAINT CHK_SYS_USER_SCOPE_TYPE CHECK (SCOPE_TYPE IN ('SITE', 'RIG', 'DEPARTMENT')),
    CONSTRAINT CHK_SYS_USER_SCOPE_TARGET CHECK (
        (SCOPE_TYPE = 'SITE' AND RIG_ID IS NULL AND DEPARTMENT_ID IS NULL) OR
        (SCOPE_TYPE = 'RIG' AND RIG_ID IS NOT NULL AND DEPARTMENT_ID IS NULL) OR
        (SCOPE_TYPE = 'DEPARTMENT' AND DEPARTMENT_ID IS NOT NULL)
    ),
    CONSTRAINT CHK_SYS_USER_SCOPE_ACCESS CHECK (CAN_VIEW IN ('Y', 'N') AND CAN_ACT IN ('Y', 'N') AND (CAN_ACT = 'N' OR CAN_VIEW = 'Y')),
    CONSTRAINT CHK_SYS_USER_SCOPE_DATES CHECK (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO >= EFFECTIVE_FROM),
    CONSTRAINT CHK_SYS_USER_SCOPE_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N')),
    CONSTRAINT CHK_SYS_USER_SCOPE_ROW_VER CHECK (ROW_VERSION >= 1)
);

CREATE INDEX IX_SYS_RIG_SITE ON SYS_RIG (SITE_ID, IS_ACTIVE);
CREATE INDEX IX_SYS_DEPT_SITE_RIG ON SYS_DEPARTMENT (SITE_ID, RIG_ID, IS_ACTIVE);
CREATE INDEX IX_SYS_SEQ_RANGE_LOOKUP ON SYS_SITE_SEQUENCE_RANGE (SEQUENCE_CODE, IS_ACTIVE, EFFECTIVE_FROM, EFFECTIVE_TO);
CREATE INDEX IX_SYS_USER_DEFAULTS ON SYS_USER (DEFAULT_SITE_ID, DEFAULT_RIG_ID, DEFAULT_DEPARTMENT_ID);
CREATE INDEX IX_SYS_USER_ROLE_USER ON SYS_USER_ROLE (USER_ID, IS_ACTIVE, ROLE_ID);
CREATE INDEX IX_SYS_ROLE_PERM_ROLE ON SYS_ROLE_PERMISSION (ROLE_ID, IS_ACTIVE, PERMISSION_ID);
CREATE INDEX IX_SYS_USER_OVR_USER ON SYS_USER_PERMISSION_OVERRIDE (USER_ID, IS_ACTIVE, PERMISSION_ID, EFFECT_CODE);
CREATE INDEX IX_SYS_USER_SCOPE_USER ON SYS_USER_DATA_SCOPE (USER_ID, IS_ACTIVE, SCOPE_TYPE);

CREATE UNIQUE INDEX UX_SYS_USER_ROLE_ACTIVE ON SYS_USER_ROLE (
    CASE WHEN IS_ACTIVE = 'Y' THEN USER_ID END,
    CASE WHEN IS_ACTIVE = 'Y' THEN ROLE_ID END
);
CREATE UNIQUE INDEX UX_SYS_ROLE_PERM_ACTIVE ON SYS_ROLE_PERMISSION (
    CASE WHEN IS_ACTIVE = 'Y' THEN ROLE_ID END,
    CASE WHEN IS_ACTIVE = 'Y' THEN PERMISSION_ID END
);
CREATE UNIQUE INDEX UX_SYS_USER_OVR_ACTIVE ON SYS_USER_PERMISSION_OVERRIDE (
    CASE WHEN IS_ACTIVE = 'Y' THEN USER_ID END,
    CASE WHEN IS_ACTIVE = 'Y' THEN PERMISSION_ID END
);
CREATE UNIQUE INDEX UX_SYS_USER_SCOPE_ACTIVE ON SYS_USER_DATA_SCOPE (
    CASE WHEN IS_ACTIVE = 'Y' THEN USER_ID END,
    CASE WHEN IS_ACTIVE = 'Y' THEN SCOPE_TYPE END,
    CASE WHEN IS_ACTIVE = 'Y' THEN SITE_ID END,
    CASE WHEN IS_ACTIVE = 'Y' THEN NVL(RIG_ID, -1) END,
    CASE WHEN IS_ACTIVE = 'Y' THEN NVL(DEPARTMENT_ID, -1) END
);
