CREATE SEQUENCE SEQ_SYS_JOB_TYPE START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_SYS_HAZARD_PROMPT START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_SYS_POSITION START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_SYS_TOOL_CATEGORY START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_SYS_TOOL START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_SYS_LANGUAGE START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_SYS_PROCEDURE_REF START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_SYS_SYSTEM_PARAMETER START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_RISK_MATRIX START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_RISK_MATRIX_VER START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_RISK_LIKELIHOOD START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_RISK_SEVERITY START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_RISK_RESULT START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_RISK_MATRIX_CELL START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_RIG_MATRIX_ASSIGN START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;

CREATE TABLE SYS_JOB_TYPE (
    JOB_TYPE_ID NUMBER(19) NOT NULL,
    JOB_TYPE_CODE VARCHAR2(50 CHAR) NOT NULL,
    JOB_TYPE_NAME VARCHAR2(200 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(2000 CHAR),
    DISPLAY_ORDER NUMBER(10) DEFAULT 0 NOT NULL,
    SCOPE_TYPE VARCHAR2(20 CHAR) DEFAULT 'GLOBAL' NOT NULL,
    SITE_ID NUMBER(19), RIG_ID NUMBER(19), DEPARTMENT_ID NUMBER(19),
    IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_SYS_JOB_TYPE PRIMARY KEY (JOB_TYPE_ID),
    CONSTRAINT FK_SYS_JOB_TYPE_SITE FOREIGN KEY (SITE_ID) REFERENCES SYS_SITE (SITE_ID),
    CONSTRAINT FK_SYS_JOB_TYPE_RIG FOREIGN KEY (RIG_ID, SITE_ID) REFERENCES SYS_RIG (RIG_ID, SITE_ID),
    CONSTRAINT FK_SYS_JOB_TYPE_DEPT FOREIGN KEY (DEPARTMENT_ID, SITE_ID) REFERENCES SYS_DEPARTMENT (DEPARTMENT_ID, SITE_ID),
    CONSTRAINT FK_SYS_JOB_TYPE_DEPT_RIG FOREIGN KEY (DEPARTMENT_ID, RIG_ID) REFERENCES SYS_DEPARTMENT (DEPARTMENT_ID, RIG_ID),
    CONSTRAINT CHK_SYS_JOB_TYPE_SCOPE CHECK ((SCOPE_TYPE='GLOBAL' AND SITE_ID IS NULL AND RIG_ID IS NULL AND DEPARTMENT_ID IS NULL) OR (SCOPE_TYPE='SITE' AND SITE_ID IS NOT NULL AND RIG_ID IS NULL AND DEPARTMENT_ID IS NULL) OR (SCOPE_TYPE='RIG' AND SITE_ID IS NOT NULL AND RIG_ID IS NOT NULL AND DEPARTMENT_ID IS NULL) OR (SCOPE_TYPE='DEPARTMENT' AND SITE_ID IS NOT NULL AND DEPARTMENT_ID IS NOT NULL)),
    CONSTRAINT CHK_SYS_JOB_TYPE_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT CHK_SYS_JOB_TYPE_ROW_VER CHECK (ROW_VERSION >= 1)
);

CREATE TABLE SYS_HAZARD_PROMPT (
    PROMPT_ID NUMBER(19) NOT NULL,
    PROMPT_CODE VARCHAR2(50 CHAR) NOT NULL,
    PROMPT_LABEL VARCHAR2(500 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(2000 CHAR), PROMPT_GROUP VARCHAR2(100 CHAR),
    DISPLAY_ORDER NUMBER(10) DEFAULT 0 NOT NULL,
    SCOPE_TYPE VARCHAR2(20 CHAR) DEFAULT 'GLOBAL' NOT NULL,
    SITE_ID NUMBER(19), RIG_ID NUMBER(19), DEPARTMENT_ID NUMBER(19),
    IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_SYS_HAZARD_PROMPT PRIMARY KEY (PROMPT_ID),
    CONSTRAINT FK_SYS_HAZARD_PROMPT_SITE FOREIGN KEY (SITE_ID) REFERENCES SYS_SITE (SITE_ID),
    CONSTRAINT FK_SYS_HAZARD_PROMPT_RIG FOREIGN KEY (RIG_ID, SITE_ID) REFERENCES SYS_RIG (RIG_ID, SITE_ID),
    CONSTRAINT CHK_SYS_HAZARD_PROMPT_SCOPE CHECK ((SCOPE_TYPE='GLOBAL' AND SITE_ID IS NULL AND RIG_ID IS NULL AND DEPARTMENT_ID IS NULL) OR (SCOPE_TYPE='SITE' AND SITE_ID IS NOT NULL AND RIG_ID IS NULL AND DEPARTMENT_ID IS NULL) OR (SCOPE_TYPE='RIG' AND SITE_ID IS NOT NULL AND RIG_ID IS NOT NULL AND DEPARTMENT_ID IS NULL)),
    CONSTRAINT CHK_SYS_HAZARD_PROMPT_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT CHK_SYS_HAZARD_PROMPT_ROW_VER CHECK (ROW_VERSION >= 1)
);

CREATE TABLE SYS_POSITION (
    POSITION_ID NUMBER(19) NOT NULL,
    POSITION_CODE VARCHAR2(50 CHAR) NOT NULL,
    POSITION_NAME VARCHAR2(200 CHAR) NOT NULL,
    ALTERNATE_NAME VARCHAR2(200 CHAR), DESCRIPTION VARCHAR2(2000 CHAR),
    DISPLAY_ORDER NUMBER(10) DEFAULT 0 NOT NULL,
    SCOPE_TYPE VARCHAR2(20 CHAR) DEFAULT 'GLOBAL' NOT NULL,
    SITE_ID NUMBER(19), RIG_ID NUMBER(19), DEPARTMENT_ID NUMBER(19),
    IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_SYS_POSITION PRIMARY KEY (POSITION_ID),
    CONSTRAINT FK_SYS_POSITION_SITE FOREIGN KEY (SITE_ID) REFERENCES SYS_SITE (SITE_ID),
    CONSTRAINT FK_SYS_POSITION_RIG FOREIGN KEY (RIG_ID, SITE_ID) REFERENCES SYS_RIG (RIG_ID, SITE_ID),
    CONSTRAINT FK_SYS_POSITION_DEPT FOREIGN KEY (DEPARTMENT_ID, SITE_ID) REFERENCES SYS_DEPARTMENT (DEPARTMENT_ID, SITE_ID),
    CONSTRAINT FK_SYS_POSITION_DEPT_RIG FOREIGN KEY (DEPARTMENT_ID, RIG_ID) REFERENCES SYS_DEPARTMENT (DEPARTMENT_ID, RIG_ID),
    CONSTRAINT CHK_SYS_POSITION_SCOPE CHECK ((SCOPE_TYPE='GLOBAL' AND SITE_ID IS NULL AND RIG_ID IS NULL AND DEPARTMENT_ID IS NULL) OR (SCOPE_TYPE='SITE' AND SITE_ID IS NOT NULL AND RIG_ID IS NULL AND DEPARTMENT_ID IS NULL) OR (SCOPE_TYPE='RIG' AND SITE_ID IS NOT NULL AND RIG_ID IS NOT NULL AND DEPARTMENT_ID IS NULL) OR (SCOPE_TYPE='DEPARTMENT' AND SITE_ID IS NOT NULL AND DEPARTMENT_ID IS NOT NULL)),
    CONSTRAINT CHK_SYS_POSITION_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT CHK_SYS_POSITION_ROW_VER CHECK (ROW_VERSION >= 1)
);

CREATE TABLE SYS_TOOL_CATEGORY (
    TOOL_CATEGORY_ID NUMBER(19) NOT NULL,
    CATEGORY_CODE VARCHAR2(50 CHAR) NOT NULL,
    CATEGORY_NAME VARCHAR2(200 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(2000 CHAR), DISPLAY_ORDER NUMBER(10) DEFAULT 0 NOT NULL,
    SCOPE_TYPE VARCHAR2(20 CHAR) DEFAULT 'GLOBAL' NOT NULL,
    SITE_ID NUMBER(19), RIG_ID NUMBER(19), DEPARTMENT_ID NUMBER(19),
    IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_SYS_TOOL_CATEGORY PRIMARY KEY (TOOL_CATEGORY_ID),
    CONSTRAINT FK_SYS_TOOL_CATEGORY_SITE FOREIGN KEY (SITE_ID) REFERENCES SYS_SITE (SITE_ID),
    CONSTRAINT FK_SYS_TOOL_CATEGORY_RIG FOREIGN KEY (RIG_ID, SITE_ID) REFERENCES SYS_RIG (RIG_ID, SITE_ID),
    CONSTRAINT FK_SYS_TOOL_CATEGORY_DEPT FOREIGN KEY (DEPARTMENT_ID, SITE_ID) REFERENCES SYS_DEPARTMENT (DEPARTMENT_ID, SITE_ID),
    CONSTRAINT FK_SYS_TOOL_CAT_DEPT_RIG FOREIGN KEY (DEPARTMENT_ID, RIG_ID) REFERENCES SYS_DEPARTMENT (DEPARTMENT_ID, RIG_ID),
    CONSTRAINT CHK_SYS_TOOL_CATEGORY_SCOPE CHECK ((SCOPE_TYPE='GLOBAL' AND SITE_ID IS NULL AND RIG_ID IS NULL AND DEPARTMENT_ID IS NULL) OR (SCOPE_TYPE='SITE' AND SITE_ID IS NOT NULL AND RIG_ID IS NULL AND DEPARTMENT_ID IS NULL) OR (SCOPE_TYPE='RIG' AND SITE_ID IS NOT NULL AND RIG_ID IS NOT NULL AND DEPARTMENT_ID IS NULL) OR (SCOPE_TYPE='DEPARTMENT' AND SITE_ID IS NOT NULL AND DEPARTMENT_ID IS NOT NULL)),
    CONSTRAINT CHK_SYS_TOOL_CATEGORY_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT CHK_SYS_TOOL_CAT_ROW_VER CHECK (ROW_VERSION >= 1)
);

CREATE TABLE SYS_TOOL (
    TOOL_ID NUMBER(19) NOT NULL,
    TOOL_CODE VARCHAR2(50 CHAR) NOT NULL, TOOL_NAME VARCHAR2(200 CHAR) NOT NULL,
    TOOL_CATEGORY_ID NUMBER(19) NOT NULL, ALTERNATE_NAME VARCHAR2(200 CHAR),
    DESCRIPTION VARCHAR2(2000 CHAR), DISPLAY_ORDER NUMBER(10) DEFAULT 0 NOT NULL,
    SCOPE_TYPE VARCHAR2(20 CHAR) DEFAULT 'GLOBAL' NOT NULL,
    SITE_ID NUMBER(19), RIG_ID NUMBER(19), DEPARTMENT_ID NUMBER(19),
    IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_SYS_TOOL PRIMARY KEY (TOOL_ID),
    CONSTRAINT FK_SYS_TOOL_CATEGORY FOREIGN KEY (TOOL_CATEGORY_ID) REFERENCES SYS_TOOL_CATEGORY (TOOL_CATEGORY_ID),
    CONSTRAINT FK_SYS_TOOL_SITE FOREIGN KEY (SITE_ID) REFERENCES SYS_SITE (SITE_ID),
    CONSTRAINT FK_SYS_TOOL_RIG FOREIGN KEY (RIG_ID, SITE_ID) REFERENCES SYS_RIG (RIG_ID, SITE_ID),
    CONSTRAINT FK_SYS_TOOL_DEPT FOREIGN KEY (DEPARTMENT_ID, SITE_ID) REFERENCES SYS_DEPARTMENT (DEPARTMENT_ID, SITE_ID),
    CONSTRAINT FK_SYS_TOOL_DEPT_RIG FOREIGN KEY (DEPARTMENT_ID, RIG_ID) REFERENCES SYS_DEPARTMENT (DEPARTMENT_ID, RIG_ID),
    CONSTRAINT CHK_SYS_TOOL_SCOPE CHECK ((SCOPE_TYPE='GLOBAL' AND SITE_ID IS NULL AND RIG_ID IS NULL AND DEPARTMENT_ID IS NULL) OR (SCOPE_TYPE='SITE' AND SITE_ID IS NOT NULL AND RIG_ID IS NULL AND DEPARTMENT_ID IS NULL) OR (SCOPE_TYPE='RIG' AND SITE_ID IS NOT NULL AND RIG_ID IS NOT NULL AND DEPARTMENT_ID IS NULL) OR (SCOPE_TYPE='DEPARTMENT' AND SITE_ID IS NOT NULL AND DEPARTMENT_ID IS NOT NULL)),
    CONSTRAINT CHK_SYS_TOOL_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT CHK_SYS_TOOL_ROW_VER CHECK (ROW_VERSION >= 1)
);

CREATE TABLE SYS_LANGUAGE (
    LANGUAGE_ID NUMBER(19) NOT NULL,
    LANGUAGE_CODE VARCHAR2(30 CHAR) NOT NULL, LANGUAGE_NAME VARCHAR2(200 CHAR) NOT NULL,
    LOCALE_CODE VARCHAR2(50 CHAR), DISPLAY_ORDER NUMBER(10) DEFAULT 0 NOT NULL,
    SCOPE_TYPE VARCHAR2(20 CHAR) DEFAULT 'GLOBAL' NOT NULL,
    SITE_ID NUMBER(19), RIG_ID NUMBER(19), DEPARTMENT_ID NUMBER(19),
    IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_SYS_LANGUAGE PRIMARY KEY (LANGUAGE_ID),
    CONSTRAINT FK_SYS_LANGUAGE_SITE FOREIGN KEY (SITE_ID) REFERENCES SYS_SITE (SITE_ID),
    CONSTRAINT FK_SYS_LANGUAGE_RIG FOREIGN KEY (RIG_ID, SITE_ID) REFERENCES SYS_RIG (RIG_ID, SITE_ID),
    CONSTRAINT FK_SYS_LANGUAGE_DEPT FOREIGN KEY (DEPARTMENT_ID, SITE_ID) REFERENCES SYS_DEPARTMENT (DEPARTMENT_ID, SITE_ID),
    CONSTRAINT FK_SYS_LANGUAGE_DEPT_RIG FOREIGN KEY (DEPARTMENT_ID, RIG_ID) REFERENCES SYS_DEPARTMENT (DEPARTMENT_ID, RIG_ID),
    CONSTRAINT CHK_SYS_LANGUAGE_SCOPE CHECK ((SCOPE_TYPE='GLOBAL' AND SITE_ID IS NULL AND RIG_ID IS NULL AND DEPARTMENT_ID IS NULL) OR (SCOPE_TYPE='SITE' AND SITE_ID IS NOT NULL AND RIG_ID IS NULL AND DEPARTMENT_ID IS NULL) OR (SCOPE_TYPE='RIG' AND SITE_ID IS NOT NULL AND RIG_ID IS NOT NULL AND DEPARTMENT_ID IS NULL) OR (SCOPE_TYPE='DEPARTMENT' AND SITE_ID IS NOT NULL AND DEPARTMENT_ID IS NOT NULL)),
    CONSTRAINT CHK_SYS_LANGUAGE_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT CHK_SYS_LANGUAGE_ROW_VER CHECK (ROW_VERSION >= 1)
);

CREATE TABLE SYS_PROCEDURE_REFERENCE (
    PROCEDURE_REFERENCE_ID NUMBER(19) NOT NULL,
    REFERENCE_CODE VARCHAR2(100 CHAR) NOT NULL, TITLE VARCHAR2(500 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(2000 CHAR), DOCUMENT_VERSION VARCHAR2(100 CHAR),
    EFFECTIVE_DATE TIMESTAMP(6), EXPIRY_DATE TIMESTAMP(6), EXTERNAL_URL VARCHAR2(1000 CHAR),
    DISPLAY_ORDER NUMBER(10) DEFAULT 0 NOT NULL,
    SCOPE_TYPE VARCHAR2(20 CHAR) DEFAULT 'GLOBAL' NOT NULL,
    SITE_ID NUMBER(19), RIG_ID NUMBER(19), DEPARTMENT_ID NUMBER(19),
    IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_SYS_PROCEDURE_REF PRIMARY KEY (PROCEDURE_REFERENCE_ID),
    CONSTRAINT FK_SYS_PROCEDURE_REF_SITE FOREIGN KEY (SITE_ID) REFERENCES SYS_SITE (SITE_ID),
    CONSTRAINT FK_SYS_PROCEDURE_REF_RIG FOREIGN KEY (RIG_ID, SITE_ID) REFERENCES SYS_RIG (RIG_ID, SITE_ID),
    CONSTRAINT CHK_SYS_PROCEDURE_REF_SCOPE CHECK ((SCOPE_TYPE='GLOBAL' AND SITE_ID IS NULL AND RIG_ID IS NULL AND DEPARTMENT_ID IS NULL) OR (SCOPE_TYPE='SITE' AND SITE_ID IS NOT NULL AND RIG_ID IS NULL AND DEPARTMENT_ID IS NULL) OR (SCOPE_TYPE='RIG' AND SITE_ID IS NOT NULL AND RIG_ID IS NOT NULL AND DEPARTMENT_ID IS NULL)),
    CONSTRAINT CHK_SYS_PROCEDURE_REF_DATES CHECK (EXPIRY_DATE IS NULL OR EFFECTIVE_DATE IS NULL OR EXPIRY_DATE >= EFFECTIVE_DATE),
    CONSTRAINT CHK_SYS_PROCEDURE_REF_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT CHK_SYS_PROCEDURE_REF_ROW_VER CHECK (ROW_VERSION >= 1)
);

CREATE TABLE SYS_SYSTEM_PARAMETER (
    SYSTEM_PARAMETER_ID NUMBER(19) NOT NULL,
    PARAMETER_KEY VARCHAR2(150 CHAR) NOT NULL, DESCRIPTION VARCHAR2(2000 CHAR),
    VALUE_TYPE VARCHAR2(20 CHAR) NOT NULL, PARAMETER_VALUE CLOB NOT NULL,
    SCOPE_TYPE VARCHAR2(20 CHAR) DEFAULT 'GLOBAL' NOT NULL,
    SITE_ID NUMBER(19), RIG_ID NUMBER(19), DEPARTMENT_ID NUMBER(19),
    IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_SYS_SYSTEM_PARAMETER PRIMARY KEY (SYSTEM_PARAMETER_ID),
    CONSTRAINT FK_SYS_SYSTEM_PARAM_SITE FOREIGN KEY (SITE_ID) REFERENCES SYS_SITE (SITE_ID),
    CONSTRAINT FK_SYS_SYSTEM_PARAM_RIG FOREIGN KEY (RIG_ID, SITE_ID) REFERENCES SYS_RIG (RIG_ID, SITE_ID),
    CONSTRAINT CHK_SYS_SYSTEM_PARAM_TYPE CHECK (VALUE_TYPE IN ('STRING','INTEGER','DECIMAL','BOOLEAN','DATE','JSON')),
    CONSTRAINT CHK_SYS_SYSTEM_PARAM_SCOPE CHECK ((SCOPE_TYPE='GLOBAL' AND SITE_ID IS NULL AND RIG_ID IS NULL AND DEPARTMENT_ID IS NULL) OR (SCOPE_TYPE='SITE' AND SITE_ID IS NOT NULL AND RIG_ID IS NULL AND DEPARTMENT_ID IS NULL) OR (SCOPE_TYPE='RIG' AND SITE_ID IS NOT NULL AND RIG_ID IS NOT NULL AND DEPARTMENT_ID IS NULL)),
    CONSTRAINT CHK_SYS_SYSTEM_PARAM_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT CHK_SYS_SYSTEM_PARAM_ROW_VER CHECK (ROW_VERSION >= 1)
);

CREATE TABLE JSA_RISK_MATRIX (
    MATRIX_ID NUMBER(19) NOT NULL, MATRIX_CODE VARCHAR2(50 CHAR) NOT NULL,
    MATRIX_NAME VARCHAR2(200 CHAR) NOT NULL, DIMENSION_SIZE NUMBER(1) NOT NULL,
    DESCRIPTION VARCHAR2(2000 CHAR), IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_JSA_RISK_MATRIX PRIMARY KEY (MATRIX_ID),
    CONSTRAINT UK_JSA_RISK_MATRIX_CODE UNIQUE (MATRIX_CODE),
    CONSTRAINT CHK_JSA_RISK_MATRIX_DIM CHECK (DIMENSION_SIZE IN (3,5)),
    CONSTRAINT CHK_JSA_RISK_MATRIX_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT CHK_JSA_RISK_MATRIX_ROW_VER CHECK (ROW_VERSION >= 1)
);

CREATE TABLE JSA_RISK_MATRIX_VERSION (
    MATRIX_VERSION_ID NUMBER(19) NOT NULL, MATRIX_ID NUMBER(19) NOT NULL,
    VERSION_CODE VARCHAR2(50 CHAR) NOT NULL, DESCRIPTION VARCHAR2(2000 CHAR),
    EFFECTIVE_FROM TIMESTAMP(6), EFFECTIVE_TO TIMESTAMP(6),
    IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_JSA_RISK_MATRIX_VER PRIMARY KEY (MATRIX_VERSION_ID),
    CONSTRAINT UK_JSA_RISK_MATRIX_VER_CODE UNIQUE (MATRIX_ID, VERSION_CODE),
    CONSTRAINT FK_JSA_RISK_MATRIX_VER_MATRIX FOREIGN KEY (MATRIX_ID) REFERENCES JSA_RISK_MATRIX (MATRIX_ID),
    CONSTRAINT CHK_JSA_RISK_MATRIX_VER_DATES CHECK (EFFECTIVE_TO IS NULL OR EFFECTIVE_FROM IS NULL OR EFFECTIVE_TO >= EFFECTIVE_FROM),
    CONSTRAINT CHK_JSA_RISK_MATRIX_VER_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT CHK_JSA_RISK_MATRIX_VER_ROW CHECK (ROW_VERSION >= 1)
);

CREATE TABLE JSA_RISK_LIKELIHOOD (
    LIKELIHOOD_ID NUMBER(19) NOT NULL, MATRIX_VERSION_ID NUMBER(19) NOT NULL,
    LIKELIHOOD_CODE VARCHAR2(30 CHAR) NOT NULL, LIKELIHOOD_LABEL VARCHAR2(300 CHAR) NOT NULL,
    NUMERIC_VALUE NUMBER(19,6), DISPLAY_ORDER NUMBER(10) NOT NULL, DEFINITION VARCHAR2(2000 CHAR) NOT NULL,
    IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_JSA_RISK_LIKELIHOOD PRIMARY KEY (LIKELIHOOD_ID),
    CONSTRAINT UK_JSA_RISK_LIK_ID_VER UNIQUE (LIKELIHOOD_ID, MATRIX_VERSION_ID),
    CONSTRAINT UK_JSA_RISK_LIK_CODE UNIQUE (MATRIX_VERSION_ID, LIKELIHOOD_CODE),
    CONSTRAINT UK_JSA_RISK_LIK_ORDER UNIQUE (MATRIX_VERSION_ID, DISPLAY_ORDER),
    CONSTRAINT FK_JSA_RISK_LIK_VERSION FOREIGN KEY (MATRIX_VERSION_ID) REFERENCES JSA_RISK_MATRIX_VERSION (MATRIX_VERSION_ID),
    CONSTRAINT CHK_JSA_RISK_LIK_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT CHK_JSA_RISK_LIK_ROW_VER CHECK (ROW_VERSION >= 1)
);

CREATE TABLE JSA_RISK_SEVERITY (
    SEVERITY_ID NUMBER(19) NOT NULL, MATRIX_VERSION_ID NUMBER(19) NOT NULL,
    SEVERITY_CODE VARCHAR2(30 CHAR) NOT NULL, SEVERITY_LABEL VARCHAR2(300 CHAR) NOT NULL,
    NUMERIC_VALUE NUMBER(19,6), DISPLAY_ORDER NUMBER(10) NOT NULL,
    GENERAL_DEFINITION VARCHAR2(2000 CHAR) NOT NULL, PEOPLE_DEFINITION VARCHAR2(2000 CHAR),
    ASSET_DEFINITION VARCHAR2(2000 CHAR), ENVIRONMENT_DEFINITION VARCHAR2(2000 CHAR),
    IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_JSA_RISK_SEVERITY PRIMARY KEY (SEVERITY_ID),
    CONSTRAINT UK_JSA_RISK_SEV_ID_VER UNIQUE (SEVERITY_ID, MATRIX_VERSION_ID),
    CONSTRAINT UK_JSA_RISK_SEV_CODE UNIQUE (MATRIX_VERSION_ID, SEVERITY_CODE),
    CONSTRAINT UK_JSA_RISK_SEV_ORDER UNIQUE (MATRIX_VERSION_ID, DISPLAY_ORDER),
    CONSTRAINT FK_JSA_RISK_SEV_VERSION FOREIGN KEY (MATRIX_VERSION_ID) REFERENCES JSA_RISK_MATRIX_VERSION (MATRIX_VERSION_ID),
    CONSTRAINT CHK_JSA_RISK_SEV_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT CHK_JSA_RISK_SEV_ROW_VER CHECK (ROW_VERSION >= 1)
);

CREATE TABLE JSA_RISK_RESULT (
    RISK_RESULT_ID NUMBER(19) NOT NULL, MATRIX_VERSION_ID NUMBER(19) NOT NULL,
    RESULT_CODE VARCHAR2(50 CHAR) NOT NULL, RESULT_NAME VARCHAR2(200 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(2000 CHAR), SEMANTIC_CATEGORY VARCHAR2(50 CHAR),
    DISPLAY_ORDER NUMBER(10) NOT NULL, DISPLAY_COLOR VARCHAR2(30 CHAR), GUIDANCE_TEXT VARCHAR2(2000 CHAR),
    PROHIBITED_FLAG CHAR(1 CHAR) DEFAULT 'N' NOT NULL, IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_JSA_RISK_RESULT PRIMARY KEY (RISK_RESULT_ID),
    CONSTRAINT UK_JSA_RISK_RESULT_ID_VER UNIQUE (RISK_RESULT_ID, MATRIX_VERSION_ID),
    CONSTRAINT UK_JSA_RISK_RESULT_CODE UNIQUE (MATRIX_VERSION_ID, RESULT_CODE),
    CONSTRAINT UK_JSA_RISK_RESULT_ORDER UNIQUE (MATRIX_VERSION_ID, DISPLAY_ORDER),
    CONSTRAINT FK_JSA_RISK_RESULT_VER FOREIGN KEY (MATRIX_VERSION_ID) REFERENCES JSA_RISK_MATRIX_VERSION (MATRIX_VERSION_ID),
    CONSTRAINT CHK_JSA_RISK_RESULT_FLAGS CHECK (PROHIBITED_FLAG IN ('Y','N') AND IS_ACTIVE IN ('Y','N')),
    CONSTRAINT CHK_JSA_RISK_RESULT_ROW CHECK (ROW_VERSION >= 1)
);

CREATE TABLE JSA_RISK_MATRIX_CELL (
    MATRIX_CELL_ID NUMBER(19) NOT NULL, MATRIX_VERSION_ID NUMBER(19) NOT NULL,
    LIKELIHOOD_ID NUMBER(19) NOT NULL, SEVERITY_ID NUMBER(19) NOT NULL,
    RATING_CODE VARCHAR2(30 CHAR), RATING_VALUE NUMBER(19,6), RISK_RESULT_ID NUMBER(19) NOT NULL,
    DISPLAY_COLOR VARCHAR2(30 CHAR), GUIDANCE_TEXT VARCHAR2(2000 CHAR),
    IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_JSA_RISK_MATRIX_CELL PRIMARY KEY (MATRIX_CELL_ID),
    CONSTRAINT UK_JSA_RISK_CELL_PAIR UNIQUE (MATRIX_VERSION_ID, LIKELIHOOD_ID, SEVERITY_ID),
    CONSTRAINT FK_JSA_RISK_CELL_VERSION FOREIGN KEY (MATRIX_VERSION_ID) REFERENCES JSA_RISK_MATRIX_VERSION (MATRIX_VERSION_ID),
    CONSTRAINT FK_JSA_RISK_CELL_LIK FOREIGN KEY (LIKELIHOOD_ID, MATRIX_VERSION_ID) REFERENCES JSA_RISK_LIKELIHOOD (LIKELIHOOD_ID, MATRIX_VERSION_ID),
    CONSTRAINT FK_JSA_RISK_CELL_SEV FOREIGN KEY (SEVERITY_ID, MATRIX_VERSION_ID) REFERENCES JSA_RISK_SEVERITY (SEVERITY_ID, MATRIX_VERSION_ID),
    CONSTRAINT FK_JSA_RISK_CELL_RESULT FOREIGN KEY (RISK_RESULT_ID, MATRIX_VERSION_ID) REFERENCES JSA_RISK_RESULT (RISK_RESULT_ID, MATRIX_VERSION_ID),
    CONSTRAINT CHK_JSA_RISK_CELL_RATING CHECK (RATING_CODE IS NOT NULL OR RATING_VALUE IS NOT NULL),
    CONSTRAINT CHK_JSA_RISK_CELL_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT CHK_JSA_RISK_CELL_ROW_VER CHECK (ROW_VERSION >= 1)
);

CREATE TABLE JSA_RIG_MATRIX_ASSIGNMENT (
    RIG_MATRIX_ASSIGNMENT_ID NUMBER(19) NOT NULL, RIG_ID NUMBER(19) NOT NULL,
    MATRIX_VERSION_ID NUMBER(19) NOT NULL, EFFECTIVE_FROM TIMESTAMP(6) NOT NULL,
    EFFECTIVE_TO TIMESTAMP(6), REASON_TEXT VARCHAR2(1000 CHAR) NOT NULL,
    IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
    ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
    CONSTRAINT PK_JSA_RIG_MATRIX_ASSIGN PRIMARY KEY (RIG_MATRIX_ASSIGNMENT_ID),
    CONSTRAINT FK_JSA_RIG_MATRIX_RIG FOREIGN KEY (RIG_ID) REFERENCES SYS_RIG (RIG_ID),
    CONSTRAINT FK_JSA_RIG_MATRIX_VERSION FOREIGN KEY (MATRIX_VERSION_ID) REFERENCES JSA_RISK_MATRIX_VERSION (MATRIX_VERSION_ID),
    CONSTRAINT CHK_JSA_RIG_MATRIX_DATES CHECK (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO > EFFECTIVE_FROM),
    CONSTRAINT CHK_JSA_RIG_MATRIX_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT CHK_JSA_RIG_MATRIX_ROW_VER CHECK (ROW_VERSION >= 1)
);

CREATE UNIQUE INDEX IX_SYS_JOB_TYPE_ACTIVE_CODE ON SYS_JOB_TYPE (CASE WHEN IS_ACTIVE='Y' THEN UPPER(JOB_TYPE_CODE) END, CASE WHEN IS_ACTIVE='Y' THEN SCOPE_TYPE END, CASE WHEN IS_ACTIVE='Y' THEN NVL(SITE_ID,-1) END, CASE WHEN IS_ACTIVE='Y' THEN NVL(RIG_ID,-1) END, CASE WHEN IS_ACTIVE='Y' THEN NVL(DEPARTMENT_ID,-1) END);
CREATE UNIQUE INDEX IX_SYS_HAZ_PROMPT_ACTIVE_CODE ON SYS_HAZARD_PROMPT (CASE WHEN IS_ACTIVE='Y' THEN UPPER(PROMPT_CODE) END, CASE WHEN IS_ACTIVE='Y' THEN SCOPE_TYPE END, CASE WHEN IS_ACTIVE='Y' THEN NVL(SITE_ID,-1) END, CASE WHEN IS_ACTIVE='Y' THEN NVL(RIG_ID,-1) END);
CREATE UNIQUE INDEX IX_SYS_POSITION_ACTIVE_CODE ON SYS_POSITION (CASE WHEN IS_ACTIVE='Y' THEN UPPER(POSITION_CODE) END, CASE WHEN IS_ACTIVE='Y' THEN SCOPE_TYPE END, CASE WHEN IS_ACTIVE='Y' THEN NVL(SITE_ID,-1) END, CASE WHEN IS_ACTIVE='Y' THEN NVL(RIG_ID,-1) END, CASE WHEN IS_ACTIVE='Y' THEN NVL(DEPARTMENT_ID,-1) END);
CREATE UNIQUE INDEX IX_SYS_TOOL_CAT_ACTIVE_CODE ON SYS_TOOL_CATEGORY (CASE WHEN IS_ACTIVE='Y' THEN UPPER(CATEGORY_CODE) END, CASE WHEN IS_ACTIVE='Y' THEN SCOPE_TYPE END, CASE WHEN IS_ACTIVE='Y' THEN NVL(SITE_ID,-1) END, CASE WHEN IS_ACTIVE='Y' THEN NVL(RIG_ID,-1) END, CASE WHEN IS_ACTIVE='Y' THEN NVL(DEPARTMENT_ID,-1) END);
CREATE UNIQUE INDEX IX_SYS_TOOL_ACTIVE_CODE ON SYS_TOOL (CASE WHEN IS_ACTIVE='Y' THEN UPPER(TOOL_CODE) END, CASE WHEN IS_ACTIVE='Y' THEN SCOPE_TYPE END, CASE WHEN IS_ACTIVE='Y' THEN NVL(SITE_ID,-1) END, CASE WHEN IS_ACTIVE='Y' THEN NVL(RIG_ID,-1) END, CASE WHEN IS_ACTIVE='Y' THEN NVL(DEPARTMENT_ID,-1) END);
CREATE UNIQUE INDEX IX_SYS_LANGUAGE_ACTIVE_CODE ON SYS_LANGUAGE (CASE WHEN IS_ACTIVE='Y' THEN UPPER(LANGUAGE_CODE) END, CASE WHEN IS_ACTIVE='Y' THEN SCOPE_TYPE END, CASE WHEN IS_ACTIVE='Y' THEN NVL(SITE_ID,-1) END, CASE WHEN IS_ACTIVE='Y' THEN NVL(RIG_ID,-1) END, CASE WHEN IS_ACTIVE='Y' THEN NVL(DEPARTMENT_ID,-1) END);
CREATE UNIQUE INDEX IX_SYS_PROC_REF_ACTIVE_CODE ON SYS_PROCEDURE_REFERENCE (CASE WHEN IS_ACTIVE='Y' THEN UPPER(REFERENCE_CODE) END, CASE WHEN IS_ACTIVE='Y' THEN SCOPE_TYPE END, CASE WHEN IS_ACTIVE='Y' THEN NVL(SITE_ID,-1) END, CASE WHEN IS_ACTIVE='Y' THEN NVL(RIG_ID,-1) END);
CREATE UNIQUE INDEX IX_SYS_SYSTEM_PARAM_ACTIVE ON SYS_SYSTEM_PARAMETER (CASE WHEN IS_ACTIVE='Y' THEN UPPER(PARAMETER_KEY) END, CASE WHEN IS_ACTIVE='Y' THEN SCOPE_TYPE END, CASE WHEN IS_ACTIVE='Y' THEN NVL(SITE_ID,-1) END, CASE WHEN IS_ACTIVE='Y' THEN NVL(RIG_ID,-1) END);

CREATE INDEX IX_SYS_JOB_TYPE_SCOPE ON SYS_JOB_TYPE (SCOPE_TYPE, SITE_ID, RIG_ID, DEPARTMENT_ID, IS_ACTIVE);
CREATE INDEX IX_SYS_HAZARD_PROMPT_SCOPE ON SYS_HAZARD_PROMPT (SCOPE_TYPE, SITE_ID, RIG_ID, IS_ACTIVE);
CREATE INDEX IX_SYS_POSITION_SCOPE ON SYS_POSITION (SCOPE_TYPE, SITE_ID, RIG_ID, DEPARTMENT_ID, IS_ACTIVE);
CREATE INDEX IX_SYS_TOOL_CATEGORY_SCOPE ON SYS_TOOL_CATEGORY (SCOPE_TYPE, SITE_ID, RIG_ID, DEPARTMENT_ID, IS_ACTIVE);
CREATE INDEX IX_SYS_TOOL_SCOPE ON SYS_TOOL (SCOPE_TYPE, SITE_ID, RIG_ID, DEPARTMENT_ID, TOOL_CATEGORY_ID, IS_ACTIVE);
CREATE INDEX IX_SYS_LANGUAGE_SCOPE ON SYS_LANGUAGE (SCOPE_TYPE, SITE_ID, RIG_ID, DEPARTMENT_ID, IS_ACTIVE);
CREATE INDEX IX_SYS_PROCEDURE_REF_SCOPE ON SYS_PROCEDURE_REFERENCE (SCOPE_TYPE, SITE_ID, RIG_ID, IS_ACTIVE);
CREATE INDEX IX_SYS_SYSTEM_PARAM_SCOPE ON SYS_SYSTEM_PARAMETER (SCOPE_TYPE, SITE_ID, RIG_ID, IS_ACTIVE);
CREATE INDEX IX_JSA_RISK_MATRIX_ACTIVE ON JSA_RISK_MATRIX (IS_ACTIVE, MATRIX_CODE);
CREATE INDEX IX_JSA_RISK_MATRIX_VER ON JSA_RISK_MATRIX_VERSION (MATRIX_ID, IS_ACTIVE, EFFECTIVE_FROM, EFFECTIVE_TO);
CREATE INDEX IX_JSA_RISK_LIK_VERSION ON JSA_RISK_LIKELIHOOD (MATRIX_VERSION_ID, IS_ACTIVE, DISPLAY_ORDER);
CREATE INDEX IX_JSA_RISK_SEV_VERSION ON JSA_RISK_SEVERITY (MATRIX_VERSION_ID, IS_ACTIVE, DISPLAY_ORDER);
CREATE INDEX IX_JSA_RISK_RESULT_VERSION ON JSA_RISK_RESULT (MATRIX_VERSION_ID, IS_ACTIVE, DISPLAY_ORDER);
CREATE INDEX IX_JSA_RISK_CELL_VERSION ON JSA_RISK_MATRIX_CELL (MATRIX_VERSION_ID, IS_ACTIVE, LIKELIHOOD_ID, SEVERITY_ID);
CREATE INDEX IX_JSA_RIG_MATRIX_PERIOD ON JSA_RIG_MATRIX_ASSIGNMENT (RIG_ID, IS_ACTIVE, EFFECTIVE_FROM, EFFECTIVE_TO);
CREATE INDEX IX_JSA_RIG_MATRIX_VERSION ON JSA_RIG_MATRIX_ASSIGNMENT (MATRIX_VERSION_ID, IS_ACTIVE, EFFECTIVE_FROM);
