CREATE SEQUENCE SEQ_JSA_BUSINESS_NUMBER START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_MASTER START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_VERSION START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_VER_PROMPT START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_VER_PROMPT_COV START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_VER_TASK START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_VER_HAZARD START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_VER_CONTROL START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_VER_BASIC_STEP START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_VER_STEP_PERF START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_VER_STEP_SUP START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_VER_STEP_TOOL START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_VER_PROC_REF START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_VER_ATTACHMENT START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;

CREATE TABLE JSA_MASTER (
  JSA_ID NUMBER(19) NOT NULL, JSA_NUMBER VARCHAR2(100 CHAR) NOT NULL,
  NUMBER_SCOPE_KEY VARCHAR2(100 CHAR) NOT NULL,
  OWNER_SITE_ID NUMBER(19) NOT NULL, RIG_ID NUMBER(19) NOT NULL, DEPARTMENT_ID NUMBER(19) NOT NULL,
  ORIGIN_SITE_ID NUMBER(19) NOT NULL, CREATED_SITE_ID NUMBER(19) NOT NULL, UPDATED_SITE_ID NUMBER(19) NOT NULL,
  CREATOR_USER_ID NUMBER(19) NOT NULL, CURRENT_VERSION_ID NUMBER(19), WORKING_VERSION_ID NUMBER(19),
  LIFECYCLE_STATUS VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
  UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
  ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JSA_MASTER PRIMARY KEY (JSA_ID),
  CONSTRAINT UK_JSA_MASTER_NUMBER UNIQUE (NUMBER_SCOPE_KEY, JSA_NUMBER),
  CONSTRAINT FK_JSA_MASTER_OWNER_SITE FOREIGN KEY (OWNER_SITE_ID) REFERENCES SYS_SITE(SITE_ID),
  CONSTRAINT FK_JSA_MASTER_RIG_SITE FOREIGN KEY (RIG_ID,OWNER_SITE_ID) REFERENCES SYS_RIG(RIG_ID,SITE_ID),
  CONSTRAINT FK_JSA_MASTER_DEPT_SITE FOREIGN KEY (DEPARTMENT_ID,OWNER_SITE_ID) REFERENCES SYS_DEPARTMENT(DEPARTMENT_ID,SITE_ID),
  CONSTRAINT FK_JSA_MASTER_DEPT_RIG FOREIGN KEY (DEPARTMENT_ID,RIG_ID) REFERENCES SYS_DEPARTMENT(DEPARTMENT_ID,RIG_ID),
  CONSTRAINT FK_JSA_MASTER_ORIGIN_SITE FOREIGN KEY (ORIGIN_SITE_ID) REFERENCES SYS_SITE(SITE_ID),
  CONSTRAINT FK_JSA_MASTER_CREATED_SITE FOREIGN KEY (CREATED_SITE_ID) REFERENCES SYS_SITE(SITE_ID),
  CONSTRAINT FK_JSA_MASTER_UPDATED_SITE FOREIGN KEY (UPDATED_SITE_ID) REFERENCES SYS_SITE(SITE_ID),
  CONSTRAINT FK_JSA_MASTER_CREATOR FOREIGN KEY (CREATOR_USER_ID) REFERENCES SYS_USER(USER_ID),
  CONSTRAINT CHK_JSA_MASTER_STATUS CHECK (LIFECYCLE_STATUS IN ('DRAFT','CANCELLED')),
  CONSTRAINT CHK_JSA_MASTER_ROW_VER CHECK (ROW_VERSION>=1)
);

CREATE TABLE JSA_VERSION (
  JSA_VERSION_ID NUMBER(19) NOT NULL, JSA_ID NUMBER(19) NOT NULL,
  VERSION_NUMBER NUMBER(10) NOT NULL, VERSION_LABEL VARCHAR2(100 CHAR), BASE_VERSION_ID NUMBER(19),
  VERSION_STATUS VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
  OWNER_SITE_ID NUMBER(19) NOT NULL, RIG_ID NUMBER(19) NOT NULL, DEPARTMENT_ID NUMBER(19) NOT NULL,
  JOB_TYPE_ID NUMBER(19) NOT NULL, MATRIX_VERSION_ID NUMBER(19) NOT NULL, LANGUAGE_ID NUMBER(19),
  JOB_TITLE VARCHAR2(500 CHAR), JOB_DESCRIPTION CLOB, LOCATION_TEXT VARCHAR2(500 CHAR),
  PERSONNEL_TEXT VARCHAR2(1000 CHAR), PTW_REQUIRED_FLAG CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  PTW_REFERENCE VARCHAR2(500 CHAR),
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
  UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
  ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JSA_VERSION PRIMARY KEY (JSA_VERSION_ID),
  CONSTRAINT UK_JSA_VERSION_MASTER UNIQUE (JSA_VERSION_ID,JSA_ID),
  CONSTRAINT UK_JSA_VERSION_NUMBER UNIQUE (JSA_ID,VERSION_NUMBER),
  CONSTRAINT FK_JSA_VERSION_MASTER FOREIGN KEY (JSA_ID) REFERENCES JSA_MASTER(JSA_ID),
  CONSTRAINT FK_JSA_VERSION_BASE FOREIGN KEY (BASE_VERSION_ID) REFERENCES JSA_VERSION(JSA_VERSION_ID),
  CONSTRAINT FK_JSA_VERSION_SITE FOREIGN KEY (OWNER_SITE_ID) REFERENCES SYS_SITE(SITE_ID),
  CONSTRAINT FK_JSA_VERSION_RIG_SITE FOREIGN KEY (RIG_ID,OWNER_SITE_ID) REFERENCES SYS_RIG(RIG_ID,SITE_ID),
  CONSTRAINT FK_JSA_VERSION_DEPT_SITE FOREIGN KEY (DEPARTMENT_ID,OWNER_SITE_ID) REFERENCES SYS_DEPARTMENT(DEPARTMENT_ID,SITE_ID),
  CONSTRAINT FK_JSA_VERSION_DEPT_RIG FOREIGN KEY (DEPARTMENT_ID,RIG_ID) REFERENCES SYS_DEPARTMENT(DEPARTMENT_ID,RIG_ID),
  CONSTRAINT FK_JSA_VERSION_JOB_TYPE FOREIGN KEY (JOB_TYPE_ID) REFERENCES SYS_JOB_TYPE(JOB_TYPE_ID),
  CONSTRAINT FK_JSA_VERSION_MATRIX FOREIGN KEY (MATRIX_VERSION_ID) REFERENCES JSA_RISK_MATRIX_VERSION(MATRIX_VERSION_ID),
  CONSTRAINT FK_JSA_VERSION_LANGUAGE FOREIGN KEY (LANGUAGE_ID) REFERENCES SYS_LANGUAGE(LANGUAGE_ID),
  CONSTRAINT CHK_JSA_VERSION_STATUS CHECK (VERSION_STATUS IN ('DRAFT','CANCELLED')),
  CONSTRAINT CHK_JSA_VERSION_PTW CHECK (PTW_REQUIRED_FLAG IN ('Y','N')),
  CONSTRAINT CHK_JSA_VERSION_BASE CHECK (BASE_VERSION_ID IS NULL OR BASE_VERSION_ID<>JSA_VERSION_ID),
  CONSTRAINT CHK_JSA_VERSION_ROW_VER CHECK (ROW_VERSION>=1)
);

ALTER TABLE JSA_MASTER ADD CONSTRAINT FK_JSA_MASTER_CURRENT_VER FOREIGN KEY (CURRENT_VERSION_ID,JSA_ID) REFERENCES JSA_VERSION(JSA_VERSION_ID,JSA_ID);
ALTER TABLE JSA_MASTER ADD CONSTRAINT FK_JSA_MASTER_WORKING_VER FOREIGN KEY (WORKING_VERSION_ID,JSA_ID) REFERENCES JSA_VERSION(JSA_VERSION_ID,JSA_ID);

CREATE TABLE JSA_VERSION_PROMPT (
  VERSION_PROMPT_ID NUMBER(19) NOT NULL, JSA_VERSION_ID NUMBER(19) NOT NULL, LOGICAL_KEY NUMBER(19) NOT NULL,
  PROMPT_ID NUMBER(19) NOT NULL, PROMPT_CODE_SNAPSHOT VARCHAR2(50 CHAR) NOT NULL, PROMPT_LABEL_SNAPSHOT VARCHAR2(500 CHAR) NOT NULL,
  SELECTED_FLAG CHAR(1 CHAR) DEFAULT 'N' NOT NULL, RESPONSE_NOTE VARCHAR2(2000 CHAR), IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL, UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL, ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JSA_VERSION_PROMPT PRIMARY KEY (VERSION_PROMPT_ID), CONSTRAINT UK_JSA_VER_PROMPT_LOG UNIQUE (JSA_VERSION_ID,LOGICAL_KEY), CONSTRAINT UK_JSA_VER_PROMPT_SRC UNIQUE (JSA_VERSION_ID,PROMPT_ID),
  CONSTRAINT FK_JSA_VER_PROMPT_VER FOREIGN KEY (JSA_VERSION_ID) REFERENCES JSA_VERSION(JSA_VERSION_ID), CONSTRAINT FK_JSA_VER_PROMPT_SRC FOREIGN KEY (PROMPT_ID) REFERENCES SYS_HAZARD_PROMPT(PROMPT_ID),
  CONSTRAINT CHK_JSA_VER_PROMPT_FLAGS CHECK (SELECTED_FLAG IN ('Y','N') AND IS_ACTIVE IN ('Y','N')), CONSTRAINT CHK_JSA_VER_PROMPT_RV CHECK (ROW_VERSION>=1)
);

CREATE TABLE JSA_VERSION_TASK (
  VERSION_TASK_ID NUMBER(19) NOT NULL, JSA_VERSION_ID NUMBER(19) NOT NULL, LOGICAL_KEY NUMBER(19) NOT NULL,
  PARENT_TASK_ID NUMBER(19), TASK_NUMBER VARCHAR2(50 CHAR), TASK_TITLE VARCHAR2(500 CHAR) NOT NULL, TASK_DESCRIPTION CLOB, DISPLAY_ORDER NUMBER(10) DEFAULT 0 NOT NULL,
  IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL, CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL, UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL, ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JSA_VERSION_TASK PRIMARY KEY (VERSION_TASK_ID), CONSTRAINT UK_JSA_VER_TASK_ID_VER UNIQUE (VERSION_TASK_ID,JSA_VERSION_ID), CONSTRAINT UK_JSA_VER_TASK_LOG UNIQUE (JSA_VERSION_ID,LOGICAL_KEY),
  CONSTRAINT FK_JSA_VER_TASK_VER FOREIGN KEY (JSA_VERSION_ID) REFERENCES JSA_VERSION(JSA_VERSION_ID), CONSTRAINT FK_JSA_VER_TASK_PARENT FOREIGN KEY (PARENT_TASK_ID,JSA_VERSION_ID) REFERENCES JSA_VERSION_TASK(VERSION_TASK_ID,JSA_VERSION_ID),
  CONSTRAINT CHK_JSA_VER_TASK_SELF CHECK (PARENT_TASK_ID IS NULL OR PARENT_TASK_ID<>VERSION_TASK_ID), CONSTRAINT CHK_JSA_VER_TASK_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')), CONSTRAINT CHK_JSA_VER_TASK_RV CHECK (ROW_VERSION>=1)
);

CREATE TABLE JSA_VERSION_HAZARD (
  VERSION_HAZARD_ID NUMBER(19) NOT NULL, JSA_VERSION_ID NUMBER(19) NOT NULL, LOGICAL_KEY NUMBER(19) NOT NULL, VERSION_TASK_ID NUMBER(19) NOT NULL,
  HAZARD_TEXT VARCHAR2(2000 CHAR) NOT NULL, INITIAL_LIKELIHOOD_ID NUMBER(19), INITIAL_SEVERITY_ID NUMBER(19), INITIAL_CELL_ID NUMBER(19), INITIAL_RATING_CODE VARCHAR2(50 CHAR), INITIAL_RESULT_CODE VARCHAR2(50 CHAR), INITIAL_RESULT_NAME VARCHAR2(200 CHAR), INITIAL_PROHIBITED_FLAG CHAR(1 CHAR),
  RESIDUAL_LIKELIHOOD_ID NUMBER(19), RESIDUAL_SEVERITY_ID NUMBER(19), RESIDUAL_CELL_ID NUMBER(19), RESIDUAL_RATING_CODE VARCHAR2(50 CHAR), RESIDUAL_RESULT_CODE VARCHAR2(50 CHAR), RESIDUAL_RESULT_NAME VARCHAR2(200 CHAR), RESIDUAL_PROHIBITED_FLAG CHAR(1 CHAR),
  DISPLAY_ORDER NUMBER(10) DEFAULT 0 NOT NULL, IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL, UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL, ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JSA_VERSION_HAZARD PRIMARY KEY (VERSION_HAZARD_ID), CONSTRAINT UK_JSA_VER_HAZ_ID_VER UNIQUE (VERSION_HAZARD_ID,VERSION_TASK_ID,JSA_VERSION_ID), CONSTRAINT UK_JSA_VER_HAZARD_LOG UNIQUE (JSA_VERSION_ID,LOGICAL_KEY),
  CONSTRAINT FK_JSA_VER_HAZARD_TASK FOREIGN KEY (VERSION_TASK_ID,JSA_VERSION_ID) REFERENCES JSA_VERSION_TASK(VERSION_TASK_ID,JSA_VERSION_ID),
  CONSTRAINT CHK_JSA_VER_HAZ_FLAGS CHECK ((INITIAL_PROHIBITED_FLAG IS NULL OR INITIAL_PROHIBITED_FLAG IN ('Y','N')) AND (RESIDUAL_PROHIBITED_FLAG IS NULL OR RESIDUAL_PROHIBITED_FLAG IN ('Y','N')) AND IS_ACTIVE IN ('Y','N')), CONSTRAINT CHK_JSA_VER_HAZ_RV CHECK (ROW_VERSION>=1)
);

ALTER TABLE JSA_VERSION_HAZARD ADD CONSTRAINT UK_JSA_VER_HAZ_ID_VER2 UNIQUE (VERSION_HAZARD_ID,JSA_VERSION_ID);

CREATE TABLE JSA_VERSION_CONTROL (
  VERSION_CONTROL_ID NUMBER(19) NOT NULL, JSA_VERSION_ID NUMBER(19) NOT NULL, VERSION_HAZARD_ID NUMBER(19) NOT NULL, LOGICAL_KEY NUMBER(19) NOT NULL,
  CONTROL_TEXT VARCHAR2(2000 CHAR) NOT NULL, DISPLAY_ORDER NUMBER(10) DEFAULT 0 NOT NULL, IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL, UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL, ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JSA_VERSION_CONTROL PRIMARY KEY (VERSION_CONTROL_ID), CONSTRAINT UK_JSA_VER_CTL_ID_HAZ UNIQUE (VERSION_CONTROL_ID,VERSION_HAZARD_ID,JSA_VERSION_ID), CONSTRAINT UK_JSA_VER_CONTROL_LOG UNIQUE (JSA_VERSION_ID,LOGICAL_KEY),
  CONSTRAINT FK_JSA_VER_CONTROL_HAZ FOREIGN KEY (VERSION_HAZARD_ID,JSA_VERSION_ID) REFERENCES JSA_VERSION_HAZARD(VERSION_HAZARD_ID,JSA_VERSION_ID),
  CONSTRAINT CHK_JSA_VER_CTL_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')), CONSTRAINT CHK_JSA_VER_CTL_RV CHECK (ROW_VERSION>=1)
);

ALTER TABLE JSA_VERSION_PROMPT ADD CONSTRAINT UK_JSA_VER_PROMPT_ID_VER UNIQUE (VERSION_PROMPT_ID,JSA_VERSION_ID);

CREATE TABLE JSA_VERSION_PROMPT_COVERAGE (
  PROMPT_COVERAGE_ID NUMBER(19) NOT NULL, JSA_VERSION_ID NUMBER(19) NOT NULL, LOGICAL_KEY NUMBER(19) NOT NULL, VERSION_PROMPT_ID NUMBER(19) NOT NULL,
  VERSION_HAZARD_ID NUMBER(19) NOT NULL, VERSION_CONTROL_ID NUMBER(19), COVERAGE_NOTE VARCHAR2(1000 CHAR), IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL, UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL, ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JSA_VER_PROMPT_COV PRIMARY KEY (PROMPT_COVERAGE_ID), CONSTRAINT UK_JSA_VER_COV_LOG UNIQUE (JSA_VERSION_ID,LOGICAL_KEY),
  CONSTRAINT FK_JSA_VER_COV_PROMPT FOREIGN KEY (VERSION_PROMPT_ID,JSA_VERSION_ID) REFERENCES JSA_VERSION_PROMPT(VERSION_PROMPT_ID,JSA_VERSION_ID),
  CONSTRAINT FK_JSA_VER_COV_HAZ FOREIGN KEY (VERSION_HAZARD_ID,JSA_VERSION_ID) REFERENCES JSA_VERSION_HAZARD(VERSION_HAZARD_ID,JSA_VERSION_ID),
  CONSTRAINT FK_JSA_VER_COV_CTL FOREIGN KEY (VERSION_CONTROL_ID,VERSION_HAZARD_ID,JSA_VERSION_ID) REFERENCES JSA_VERSION_CONTROL(VERSION_CONTROL_ID,VERSION_HAZARD_ID,JSA_VERSION_ID),
  CONSTRAINT CHK_JSA_VER_COV_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')), CONSTRAINT CHK_JSA_VER_COV_RV CHECK (ROW_VERSION>=1)
);

CREATE TABLE JSA_VERSION_BASIC_STEP (
  BASIC_STEP_ID NUMBER(19) NOT NULL, JSA_VERSION_ID NUMBER(19) NOT NULL, LOGICAL_KEY NUMBER(19) NOT NULL, VERSION_TASK_ID NUMBER(19),
  STEP_NUMBER VARCHAR2(50 CHAR), STEP_TEXT VARCHAR2(2000 CHAR) NOT NULL, DISPLAY_ORDER NUMBER(10) DEFAULT 0 NOT NULL, NO_TOOL_REQUIRED_FLAG CHAR(1 CHAR) DEFAULT 'N' NOT NULL, IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL, UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL, ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JSA_VERSION_BASIC_STEP PRIMARY KEY (BASIC_STEP_ID), CONSTRAINT UK_JSA_VER_STEP_ID_VER UNIQUE (BASIC_STEP_ID,JSA_VERSION_ID), CONSTRAINT UK_JSA_VER_STEP_LOG UNIQUE (JSA_VERSION_ID,LOGICAL_KEY),
  CONSTRAINT FK_JSA_VER_STEP_VER FOREIGN KEY (JSA_VERSION_ID) REFERENCES JSA_VERSION(JSA_VERSION_ID), CONSTRAINT FK_JSA_VER_STEP_TASK FOREIGN KEY (VERSION_TASK_ID,JSA_VERSION_ID) REFERENCES JSA_VERSION_TASK(VERSION_TASK_ID,JSA_VERSION_ID),
  CONSTRAINT CHK_JSA_VER_STEP_FLAGS CHECK (NO_TOOL_REQUIRED_FLAG IN ('Y','N') AND IS_ACTIVE IN ('Y','N')), CONSTRAINT CHK_JSA_VER_STEP_RV CHECK (ROW_VERSION>=1)
);

CREATE TABLE JSA_VER_BASIC_STEP_PERFORMER (
  STEP_PERFORMER_ID NUMBER(19) NOT NULL, JSA_VERSION_ID NUMBER(19) NOT NULL, BASIC_STEP_ID NUMBER(19) NOT NULL, LOGICAL_KEY NUMBER(19) NOT NULL, POSITION_ID NUMBER(19) NOT NULL,
  POSITION_CODE_SNAPSHOT VARCHAR2(50 CHAR) NOT NULL, POSITION_NAME_SNAPSHOT VARCHAR2(200 CHAR) NOT NULL, DISPLAY_ORDER NUMBER(10) DEFAULT 0 NOT NULL, IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL, UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL, ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JSA_VER_STEP_PERF PRIMARY KEY (STEP_PERFORMER_ID), CONSTRAINT UK_JSA_VER_STEP_PERF_LOG UNIQUE (JSA_VERSION_ID,LOGICAL_KEY), CONSTRAINT FK_JSA_STEP_PERF_STEP FOREIGN KEY (BASIC_STEP_ID,JSA_VERSION_ID) REFERENCES JSA_VERSION_BASIC_STEP(BASIC_STEP_ID,JSA_VERSION_ID), CONSTRAINT FK_JSA_STEP_PERF_POS FOREIGN KEY (POSITION_ID) REFERENCES SYS_POSITION(POSITION_ID), CONSTRAINT CHK_JSA_STEP_PERF_ACT CHECK (IS_ACTIVE IN ('Y','N')), CONSTRAINT CHK_JSA_STEP_PERF_RV CHECK (ROW_VERSION>=1)
);

CREATE TABLE JSA_VER_BASIC_STEP_SUPERVISOR (
  STEP_SUPERVISOR_ID NUMBER(19) NOT NULL, JSA_VERSION_ID NUMBER(19) NOT NULL, BASIC_STEP_ID NUMBER(19) NOT NULL, LOGICAL_KEY NUMBER(19) NOT NULL, POSITION_ID NUMBER(19) NOT NULL,
  POSITION_CODE_SNAPSHOT VARCHAR2(50 CHAR) NOT NULL, POSITION_NAME_SNAPSHOT VARCHAR2(200 CHAR) NOT NULL, DISPLAY_ORDER NUMBER(10) DEFAULT 0 NOT NULL, IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL, UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL, ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JSA_VER_STEP_SUP PRIMARY KEY (STEP_SUPERVISOR_ID), CONSTRAINT UK_JSA_VER_STEP_SUP_LOG UNIQUE (JSA_VERSION_ID,LOGICAL_KEY), CONSTRAINT FK_JSA_STEP_SUP_STEP FOREIGN KEY (BASIC_STEP_ID,JSA_VERSION_ID) REFERENCES JSA_VERSION_BASIC_STEP(BASIC_STEP_ID,JSA_VERSION_ID), CONSTRAINT FK_JSA_STEP_SUP_POS FOREIGN KEY (POSITION_ID) REFERENCES SYS_POSITION(POSITION_ID), CONSTRAINT CHK_JSA_STEP_SUP_ACT CHECK (IS_ACTIVE IN ('Y','N')), CONSTRAINT CHK_JSA_STEP_SUP_RV CHECK (ROW_VERSION>=1)
);

CREATE TABLE JSA_VER_BASIC_STEP_TOOL (
  STEP_TOOL_ID NUMBER(19) NOT NULL, JSA_VERSION_ID NUMBER(19) NOT NULL, BASIC_STEP_ID NUMBER(19) NOT NULL, LOGICAL_KEY NUMBER(19) NOT NULL, TOOL_ID NUMBER(19) NOT NULL,
  TOOL_CODE_SNAPSHOT VARCHAR2(50 CHAR) NOT NULL, TOOL_NAME_SNAPSHOT VARCHAR2(200 CHAR) NOT NULL, DISPLAY_ORDER NUMBER(10) DEFAULT 0 NOT NULL, IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL, UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL, ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JSA_VER_STEP_TOOL PRIMARY KEY (STEP_TOOL_ID), CONSTRAINT UK_JSA_VER_STEP_TOOL_LOG UNIQUE (JSA_VERSION_ID,LOGICAL_KEY), CONSTRAINT FK_JSA_STEP_TOOL_STEP FOREIGN KEY (BASIC_STEP_ID,JSA_VERSION_ID) REFERENCES JSA_VERSION_BASIC_STEP(BASIC_STEP_ID,JSA_VERSION_ID), CONSTRAINT FK_JSA_STEP_TOOL_SRC FOREIGN KEY (TOOL_ID) REFERENCES SYS_TOOL(TOOL_ID), CONSTRAINT CHK_JSA_STEP_TOOL_ACT CHECK (IS_ACTIVE IN ('Y','N')), CONSTRAINT CHK_JSA_STEP_TOOL_RV CHECK (ROW_VERSION>=1)
);

CREATE TABLE JSA_VERSION_PROCEDURE_REF (
  VERSION_PROCEDURE_REF_ID NUMBER(19) NOT NULL, JSA_VERSION_ID NUMBER(19) NOT NULL, LOGICAL_KEY NUMBER(19) NOT NULL, PROCEDURE_REFERENCE_ID NUMBER(19),
  REFERENCE_CODE_SNAPSHOT VARCHAR2(100 CHAR) NOT NULL, REFERENCE_TITLE_SNAPSHOT VARCHAR2(500 CHAR) NOT NULL, REVISION_SNAPSHOT VARCHAR2(100 CHAR), URI_SNAPSHOT VARCHAR2(1000 CHAR), NOTES_TEXT VARCHAR2(1000 CHAR), DISPLAY_ORDER NUMBER(10) DEFAULT 0 NOT NULL, IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL, UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL, ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JSA_VERSION_PROC_REF PRIMARY KEY (VERSION_PROCEDURE_REF_ID), CONSTRAINT UK_JSA_VER_PROC_LOG UNIQUE (JSA_VERSION_ID,LOGICAL_KEY), CONSTRAINT FK_JSA_VER_PROC_VER FOREIGN KEY (JSA_VERSION_ID) REFERENCES JSA_VERSION(JSA_VERSION_ID), CONSTRAINT FK_JSA_VER_PROC_SRC FOREIGN KEY (PROCEDURE_REFERENCE_ID) REFERENCES SYS_PROCEDURE_REFERENCE(PROCEDURE_REFERENCE_ID), CONSTRAINT CHK_JSA_VER_PROC_ACT CHECK (IS_ACTIVE IN ('Y','N')), CONSTRAINT CHK_JSA_VER_PROC_RV CHECK (ROW_VERSION>=1)
);

CREATE TABLE JSA_VERSION_ATTACHMENT (
  VERSION_ATTACHMENT_ID NUMBER(19) NOT NULL, JSA_VERSION_ID NUMBER(19) NOT NULL, LOGICAL_KEY NUMBER(19) NOT NULL,
  FILE_NAME VARCHAR2(500 CHAR) NOT NULL, CONTENT_TYPE VARCHAR2(200 CHAR), FILE_SIZE NUMBER(19), STORAGE_KEY VARCHAR2(1000 CHAR), ATTACHMENT_STATUS VARCHAR2(30 CHAR) DEFAULT 'METADATA_ONLY' NOT NULL, DESCRIPTION VARCHAR2(1000 CHAR), IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, CREATED_BY VARCHAR2(255 CHAR) NOT NULL, UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_BY VARCHAR2(255 CHAR) NOT NULL, ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JSA_VERSION_ATTACHMENT PRIMARY KEY (VERSION_ATTACHMENT_ID), CONSTRAINT UK_JSA_VER_ATTACH_LOG UNIQUE (JSA_VERSION_ID,LOGICAL_KEY), CONSTRAINT FK_JSA_VER_ATTACH_VER FOREIGN KEY (JSA_VERSION_ID) REFERENCES JSA_VERSION(JSA_VERSION_ID), CONSTRAINT CHK_JSA_VER_ATTACH_STATUS CHECK (ATTACHMENT_STATUS IN ('METADATA_ONLY','STORED','FAILED','REMOVED')), CONSTRAINT CHK_JSA_VER_ATTACH_ACT CHECK (IS_ACTIVE IN ('Y','N')), CONSTRAINT CHK_JSA_VER_ATTACH_SIZE CHECK (FILE_SIZE IS NULL OR FILE_SIZE>=0), CONSTRAINT CHK_JSA_VER_ATTACH_RV CHECK (ROW_VERSION>=1)
);

CREATE INDEX IX_JSA_MASTER_OWNER ON JSA_MASTER(OWNER_SITE_ID,RIG_ID,DEPARTMENT_ID,LIFECYCLE_STATUS);
CREATE INDEX IX_JSA_VERSION_MASTER ON JSA_VERSION(JSA_ID,VERSION_STATUS);
CREATE INDEX IX_JSA_VER_PROMPT_ACTIVE ON JSA_VERSION_PROMPT(JSA_VERSION_ID,IS_ACTIVE,SELECTED_FLAG);
CREATE INDEX IX_JSA_VER_TASK_ACTIVE ON JSA_VERSION_TASK(JSA_VERSION_ID,IS_ACTIVE,DISPLAY_ORDER);
CREATE INDEX IX_JSA_VER_HAZ_ACTIVE ON JSA_VERSION_HAZARD(JSA_VERSION_ID,VERSION_TASK_ID,IS_ACTIVE,DISPLAY_ORDER);
CREATE INDEX IX_JSA_VER_CTL_ACTIVE ON JSA_VERSION_CONTROL(JSA_VERSION_ID,VERSION_HAZARD_ID,IS_ACTIVE,DISPLAY_ORDER);
CREATE INDEX IX_JSA_VER_COV_ACTIVE ON JSA_VERSION_PROMPT_COVERAGE(JSA_VERSION_ID,VERSION_PROMPT_ID,IS_ACTIVE);
CREATE INDEX IX_JSA_VER_STEP_ACTIVE ON JSA_VERSION_BASIC_STEP(JSA_VERSION_ID,IS_ACTIVE,DISPLAY_ORDER);
CREATE INDEX IX_JSA_VER_PROC_ACTIVE ON JSA_VERSION_PROCEDURE_REF(JSA_VERSION_ID,IS_ACTIVE,DISPLAY_ORDER);
CREATE INDEX IX_JSA_VER_ATTACH_ACTIVE ON JSA_VERSION_ATTACHMENT(JSA_VERSION_ID,IS_ACTIVE);
