ALTER TABLE JSA_MASTER DROP CONSTRAINT CHK_JSA_MASTER_STATUS;
ALTER TABLE JSA_MASTER ADD CONSTRAINT CHK_JSA_MASTER_STATUS CHECK (LIFECYCLE_STATUS IN ('DRAFT','PUBLISHED','CANCELLED'));
ALTER TABLE JSA_VERSION DROP CONSTRAINT CHK_JSA_VERSION_STATUS;
ALTER TABLE JSA_VERSION MODIFY VERSION_STATUS VARCHAR2(30 CHAR);
ALTER TABLE JSA_VERSION ADD CONSTRAINT CHK_JSA_VERSION_STATUS CHECK (VERSION_STATUS IN ('DRAFT','DEPARTMENT_HEAD_REVIEW','STC_REVIEW','OIM_REVIEW','RIG_MANAGER_REVIEW','RETURNED','REJECTED','PUBLISHED','CANCELLED'));
ALTER TABLE JSA_VERSION ADD (
  PUBLISHED_AT TIMESTAMP(6),
  PUBLISHED_BY_USER_ID NUMBER(19),
  PUBLISHED_BY_USERNAME VARCHAR2(255 CHAR),
  CONSTRAINT FK_JSA_VER_PUBLISHED_BY FOREIGN KEY (PUBLISHED_BY_USER_ID) REFERENCES SYS_USER(USER_ID),
  CONSTRAINT CHK_JSA_VER_PUBLISHED CHECK (
    (VERSION_STATUS='PUBLISHED' AND PUBLISHED_AT IS NOT NULL AND PUBLISHED_BY_USER_ID IS NOT NULL AND PUBLISHED_BY_USERNAME IS NOT NULL)
    OR (VERSION_STATUS<>'PUBLISHED' AND PUBLISHED_AT IS NULL AND PUBLISHED_BY_USER_ID IS NULL AND PUBLISHED_BY_USERNAME IS NULL)
  )
);

CREATE SEQUENCE SEQ_JSA_WORKFLOW_DEF START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_WORKFLOW_STEP START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_WORKFLOW_BIND START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_WF_ROLE_ASSIGN START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_WORKFLOW_INST START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_WORKFLOW_TASK START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_WORKFLOW_ACTION START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_SYS_NOTIFICATION START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_SYS_NOTIF_OUTBOX START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;

CREATE TABLE JSA_WORKFLOW_DEFINITION (
  DEFINITION_ID NUMBER(19) NOT NULL,
  DEFINITION_CODE VARCHAR2(50 CHAR) NOT NULL,
  VERSION_NUMBER NUMBER(10) NOT NULL,
  DEFINITION_NAME VARCHAR2(200 CHAR) NOT NULL,
  STATUS_CODE VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
  EFFECTIVE_FROM TIMESTAMP(6),
  EFFECTIVE_TO TIMESTAMP(6),
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
  UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
  ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JSA_WORKFLOW_DEF PRIMARY KEY (DEFINITION_ID),
  CONSTRAINT UK_JSA_WF_DEF_VERSION UNIQUE (DEFINITION_CODE,VERSION_NUMBER),
  CONSTRAINT CHK_JSA_WF_DEF_STATUS CHECK (STATUS_CODE IN ('DRAFT','ACTIVE','INACTIVE')),
  CONSTRAINT CHK_JSA_WF_DEF_DATES CHECK (EFFECTIVE_TO IS NULL OR EFFECTIVE_FROM IS NULL OR EFFECTIVE_TO>=EFFECTIVE_FROM),
  CONSTRAINT CHK_JSA_WF_DEF_ROW_VER CHECK (ROW_VERSION>=1)
);

CREATE TABLE JSA_WORKFLOW_STEP (
  STEP_ID NUMBER(19) NOT NULL,
  DEFINITION_ID NUMBER(19) NOT NULL,
  STEP_ORDER NUMBER(10) NOT NULL,
  STEP_CODE VARCHAR2(50 CHAR) NOT NULL,
  STEP_NAME VARCHAR2(200 CHAR) NOT NULL,
  VERSION_STATUS VARCHAR2(30 CHAR) NOT NULL,
  WORKFLOW_ROLE_CODE VARCHAR2(50 CHAR) NOT NULL,
  RESOLVER_TYPE VARCHAR2(30 CHAR) DEFAULT 'UNIQUE_ROLE_SCOPE' NOT NULL,
  OPTIONAL_FLAG CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  CONDITION_TYPE VARCHAR2(30 CHAR) DEFAULT 'ALWAYS' NOT NULL,
  CONDITION_VALUE VARCHAR2(200 CHAR),
  IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
  UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
  ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JSA_WORKFLOW_STEP PRIMARY KEY (STEP_ID),
  CONSTRAINT UK_JSA_WF_STEP_ORDER UNIQUE (DEFINITION_ID,STEP_ORDER),
  CONSTRAINT UK_JSA_WF_STEP_CODE UNIQUE (DEFINITION_ID,STEP_CODE),
  CONSTRAINT FK_JSA_WF_STEP_DEF FOREIGN KEY (DEFINITION_ID) REFERENCES JSA_WORKFLOW_DEFINITION(DEFINITION_ID),
  CONSTRAINT CHK_JSA_WF_STEP_STATUS CHECK (VERSION_STATUS IN ('DEPARTMENT_HEAD_REVIEW','STC_REVIEW','OIM_REVIEW','RIG_MANAGER_REVIEW')),
  CONSTRAINT CHK_JSA_WF_STEP_RESOLVER CHECK (RESOLVER_TYPE IN ('UNIQUE_ROLE_SCOPE')),
  CONSTRAINT CHK_JSA_WF_STEP_COND CHECK (CONDITION_TYPE IN ('ALWAYS','TEST_FLAG','RIG_MANAGER_CONFIG')),
  CONSTRAINT CHK_JSA_WF_STEP_FLAGS CHECK (OPTIONAL_FLAG IN ('Y','N') AND IS_ACTIVE IN ('Y','N')),
  CONSTRAINT CHK_JSA_WF_STEP_ORDER_POS CHECK (STEP_ORDER>0),
  CONSTRAINT CHK_JSA_WF_STEP_ROW_VER CHECK (ROW_VERSION>=1)
);

CREATE TABLE JSA_WORKFLOW_BINDING (
  BINDING_ID NUMBER(19) NOT NULL,
  DEFINITION_ID NUMBER(19) NOT NULL,
  SITE_ID NUMBER(19),
  RIG_ID NUMBER(19),
  DEPARTMENT_ID NUMBER(19),
  JOB_TYPE_ID NUMBER(19),
  PRIORITY_NUMBER NUMBER(10) DEFAULT 100 NOT NULL,
  EFFECTIVE_FROM TIMESTAMP(6) NOT NULL,
  EFFECTIVE_TO TIMESTAMP(6),
  IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
  UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
  ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JSA_WORKFLOW_BIND PRIMARY KEY (BINDING_ID),
  CONSTRAINT FK_JSA_WF_BIND_DEF FOREIGN KEY (DEFINITION_ID) REFERENCES JSA_WORKFLOW_DEFINITION(DEFINITION_ID),
  CONSTRAINT FK_JSA_WF_BIND_SITE FOREIGN KEY (SITE_ID) REFERENCES SYS_SITE(SITE_ID),
  CONSTRAINT FK_JSA_WF_BIND_RIG FOREIGN KEY (RIG_ID,SITE_ID) REFERENCES SYS_RIG(RIG_ID,SITE_ID),
  CONSTRAINT FK_JSA_WF_BIND_DEPT FOREIGN KEY (DEPARTMENT_ID,SITE_ID) REFERENCES SYS_DEPARTMENT(DEPARTMENT_ID,SITE_ID),
  CONSTRAINT FK_JSA_WF_BIND_JOB FOREIGN KEY (JOB_TYPE_ID) REFERENCES SYS_JOB_TYPE(JOB_TYPE_ID),
  CONSTRAINT CHK_JSA_WF_BIND_SCOPE CHECK ((RIG_ID IS NULL OR SITE_ID IS NOT NULL) AND (DEPARTMENT_ID IS NULL OR SITE_ID IS NOT NULL)),
  CONSTRAINT CHK_JSA_WF_BIND_DATES CHECK (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO>=EFFECTIVE_FROM),
  CONSTRAINT CHK_JSA_WF_BIND_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
  CONSTRAINT CHK_JSA_WF_BIND_ROW_VER CHECK (ROW_VERSION>=1)
);

CREATE TABLE JSA_WF_ROLE_ASSIGNMENT (
  ROLE_ASSIGNMENT_ID NUMBER(19) NOT NULL,
  WORKFLOW_ROLE_CODE VARCHAR2(50 CHAR) NOT NULL,
  USER_ID NUMBER(19) NOT NULL,
  SITE_ID NUMBER(19) NOT NULL,
  RIG_ID NUMBER(19),
  DEPARTMENT_ID NUMBER(19),
  EFFECTIVE_FROM TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  EFFECTIVE_TO TIMESTAMP(6),
  IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
  UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
  ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JSA_WF_ROLE_ASSIGN PRIMARY KEY (ROLE_ASSIGNMENT_ID),
  CONSTRAINT FK_JSA_WF_ROLE_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USER(USER_ID),
  CONSTRAINT FK_JSA_WF_ROLE_SITE FOREIGN KEY (SITE_ID) REFERENCES SYS_SITE(SITE_ID),
  CONSTRAINT FK_JSA_WF_ROLE_RIG FOREIGN KEY (RIG_ID,SITE_ID) REFERENCES SYS_RIG(RIG_ID,SITE_ID),
  CONSTRAINT FK_JSA_WF_ROLE_DEPT FOREIGN KEY (DEPARTMENT_ID,SITE_ID) REFERENCES SYS_DEPARTMENT(DEPARTMENT_ID,SITE_ID),
  CONSTRAINT CHK_JSA_WF_ROLE_DATES CHECK (EFFECTIVE_TO IS NULL OR EFFECTIVE_TO>=EFFECTIVE_FROM),
  CONSTRAINT CHK_JSA_WF_ROLE_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
  CONSTRAINT CHK_JSA_WF_ROLE_ROW_VER CHECK (ROW_VERSION>=1)
);

CREATE TABLE JSA_WORKFLOW_INSTANCE (
  INSTANCE_ID NUMBER(19) NOT NULL,
  JSA_ID NUMBER(19) NOT NULL,
  JSA_VERSION_ID NUMBER(19) NOT NULL,
  DEFINITION_ID NUMBER(19) NOT NULL,
  BINDING_ID NUMBER(19) NOT NULL,
  INSTANCE_STATUS VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
  CURRENT_STEP_ORDER NUMBER(10),
  CYCLE_NUMBER NUMBER(10) DEFAULT 1 NOT NULL,
  STARTED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  COMPLETED_AT TIMESTAMP(6),
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
  UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
  ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JSA_WORKFLOW_INST PRIMARY KEY (INSTANCE_ID),
  CONSTRAINT UK_JSA_WF_INST_VERSION UNIQUE (JSA_VERSION_ID),
  CONSTRAINT FK_JSA_WF_INST_VERSION FOREIGN KEY (JSA_VERSION_ID,JSA_ID) REFERENCES JSA_VERSION(JSA_VERSION_ID,JSA_ID),
  CONSTRAINT FK_JSA_WF_INST_DEF FOREIGN KEY (DEFINITION_ID) REFERENCES JSA_WORKFLOW_DEFINITION(DEFINITION_ID),
  CONSTRAINT FK_JSA_WF_INST_BIND FOREIGN KEY (BINDING_ID) REFERENCES JSA_WORKFLOW_BINDING(BINDING_ID),
  CONSTRAINT CHK_JSA_WF_INST_STATUS CHECK (INSTANCE_STATUS IN ('ACTIVE','RETURNED','COMPLETED','REJECTED','CANCELLED')),
  CONSTRAINT CHK_JSA_WF_INST_CYCLE CHECK (CYCLE_NUMBER>0),
  CONSTRAINT CHK_JSA_WF_INST_ROW_VER CHECK (ROW_VERSION>=1)
);

CREATE TABLE JSA_WORKFLOW_TASK (
  WORKFLOW_TASK_ID NUMBER(19) NOT NULL,
  INSTANCE_ID NUMBER(19) NOT NULL,
  STEP_ID NUMBER(19) NOT NULL,
  CYCLE_NUMBER NUMBER(10) NOT NULL,
  ASSIGNEE_USER_ID NUMBER(19) NOT NULL,
  TASK_STATUS VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
  ASSIGNED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  COMPLETED_AT TIMESTAMP(6),
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
  UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
  ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JSA_WORKFLOW_TASK PRIMARY KEY (WORKFLOW_TASK_ID),
  CONSTRAINT UK_JSA_WF_TASK_CYCLE UNIQUE (INSTANCE_ID,STEP_ID,CYCLE_NUMBER),
  CONSTRAINT FK_JSA_WF_TASK_INST FOREIGN KEY (INSTANCE_ID) REFERENCES JSA_WORKFLOW_INSTANCE(INSTANCE_ID),
  CONSTRAINT FK_JSA_WF_TASK_STEP FOREIGN KEY (STEP_ID) REFERENCES JSA_WORKFLOW_STEP(STEP_ID),
  CONSTRAINT FK_JSA_WF_TASK_USER FOREIGN KEY (ASSIGNEE_USER_ID) REFERENCES SYS_USER(USER_ID),
  CONSTRAINT CHK_JSA_WF_TASK_STATUS CHECK (TASK_STATUS IN ('PENDING','APPROVED','RETURNED','REJECTED','CANCELLED')),
  CONSTRAINT CHK_JSA_WF_TASK_ROW_VER CHECK (ROW_VERSION>=1)
);

CREATE TABLE JSA_WORKFLOW_ACTION (
  ACTION_ID NUMBER(19) NOT NULL,
  INSTANCE_ID NUMBER(19) NOT NULL,
  WORKFLOW_TASK_ID NUMBER(19),
  CYCLE_NUMBER NUMBER(10) NOT NULL,
  ACTION_CODE VARCHAR2(20 CHAR) NOT NULL,
  ACTOR_USER_ID NUMBER(19) NOT NULL,
  ACTOR_USERNAME VARCHAR2(255 CHAR) NOT NULL,
  FROM_STATUS VARCHAR2(30 CHAR),
  TO_STATUS VARCHAR2(30 CHAR),
  COMMENT_TEXT VARCHAR2(2000 CHAR),
  CORRELATION_ID VARCHAR2(100 CHAR) NOT NULL,
  ACTION_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_JSA_WORKFLOW_ACTION PRIMARY KEY (ACTION_ID),
  CONSTRAINT FK_JSA_WF_ACTION_INST FOREIGN KEY (INSTANCE_ID) REFERENCES JSA_WORKFLOW_INSTANCE(INSTANCE_ID),
  CONSTRAINT FK_JSA_WF_ACTION_TASK FOREIGN KEY (WORKFLOW_TASK_ID) REFERENCES JSA_WORKFLOW_TASK(WORKFLOW_TASK_ID),
  CONSTRAINT FK_JSA_WF_ACTION_USER FOREIGN KEY (ACTOR_USER_ID) REFERENCES SYS_USER(USER_ID),
  CONSTRAINT CHK_JSA_WF_ACTION_CODE CHECK (ACTION_CODE IN ('SUBMIT','RESUBMIT','APPROVE','RETURN','REJECT','COMMENT','PUBLISH'))
);

CREATE TABLE SYS_NOTIFICATION (
  NOTIFICATION_ID NUMBER(19) NOT NULL,
  RECIPIENT_USER_ID NUMBER(19) NOT NULL,
  NOTIFICATION_TYPE VARCHAR2(50 CHAR) NOT NULL,
  SUBJECT_TEXT VARCHAR2(500 CHAR) NOT NULL,
  BODY_TEXT VARCHAR2(2000 CHAR) NOT NULL,
  TARGET_TYPE VARCHAR2(50 CHAR) NOT NULL,
  TARGET_ID NUMBER(19) NOT NULL,
  READ_FLAG CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
  CONSTRAINT PK_SYS_NOTIFICATION PRIMARY KEY (NOTIFICATION_ID),
  CONSTRAINT FK_SYS_NOTIFICATION_USER FOREIGN KEY (RECIPIENT_USER_ID) REFERENCES SYS_USER(USER_ID),
  CONSTRAINT CHK_SYS_NOTIFICATION_READ CHECK (READ_FLAG IN ('Y','N'))
);

CREATE TABLE SYS_NOTIFICATION_OUTBOX (
  OUTBOX_ID NUMBER(19) NOT NULL,
  NOTIFICATION_ID NUMBER(19) NOT NULL,
  CHANNEL_CODE VARCHAR2(20 CHAR) DEFAULT 'IN_APP' NOT NULL,
  DELIVERY_STATUS VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
  ATTEMPT_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
  AVAILABLE_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  DELIVERED_AT TIMESTAMP(6),
  LAST_ERROR VARCHAR2(1000 CHAR),
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
  CONSTRAINT PK_SYS_NOTIF_OUTBOX PRIMARY KEY (OUTBOX_ID),
  CONSTRAINT FK_SYS_NOTIF_OUTBOX_NOTE FOREIGN KEY (NOTIFICATION_ID) REFERENCES SYS_NOTIFICATION(NOTIFICATION_ID),
  CONSTRAINT CHK_SYS_NOTIF_CHANNEL CHECK (CHANNEL_CODE IN ('IN_APP','EMAIL')),
  CONSTRAINT CHK_SYS_NOTIF_STATUS CHECK (DELIVERY_STATUS IN ('PENDING','DELIVERED','FAILED')),
  CONSTRAINT CHK_SYS_NOTIF_ATTEMPT CHECK (ATTEMPT_COUNT>=0)
);

CREATE INDEX IX_JSA_WF_BIND_LOOKUP ON JSA_WORKFLOW_BINDING(IS_ACTIVE,SITE_ID,RIG_ID,DEPARTMENT_ID,JOB_TYPE_ID,EFFECTIVE_FROM,EFFECTIVE_TO);
CREATE INDEX IX_JSA_WF_ROLE_LOOKUP ON JSA_WF_ROLE_ASSIGNMENT(WORKFLOW_ROLE_CODE,SITE_ID,RIG_ID,DEPARTMENT_ID,IS_ACTIVE);
CREATE INDEX IX_JSA_WF_TASK_ASSIGNEE ON JSA_WORKFLOW_TASK(ASSIGNEE_USER_ID,TASK_STATUS,ASSIGNED_AT);
CREATE INDEX IX_JSA_WF_ACTION_INST ON JSA_WORKFLOW_ACTION(INSTANCE_ID,ACTION_AT);
CREATE INDEX IX_SYS_NOTIFICATION_USER ON SYS_NOTIFICATION(RECIPIENT_USER_ID,READ_FLAG,CREATED_AT);
CREATE INDEX IX_SYS_NOTIF_OUTBOX_STATUS ON SYS_NOTIFICATION_OUTBOX(DELIVERY_STATUS,AVAILABLE_AT);
/

CREATE OR REPLACE PROCEDURE JSA_ASSERT_VERSION_MUTABLE(P_VERSION_ID NUMBER) AS
  V_STATUS JSA_VERSION.VERSION_STATUS%TYPE;
BEGIN
  SELECT VERSION_STATUS INTO V_STATUS FROM JSA_VERSION WHERE JSA_VERSION_ID=P_VERSION_ID;
  IF V_STATUS='PUBLISHED' THEN
    RAISE_APPLICATION_ERROR(-20041,'Published JSA Version is immutable');
  END IF;
END;
/
CREATE OR REPLACE TRIGGER TRG_JSA_VER_IMMUTABLE BEFORE UPDATE OR DELETE ON JSA_VERSION FOR EACH ROW
BEGIN
  IF :OLD.VERSION_STATUS='PUBLISHED' THEN RAISE_APPLICATION_ERROR(-20041,'Published JSA Version is immutable'); END IF;
END;
/
CREATE OR REPLACE TRIGGER TRG_JSA_PROMPT_IMMUTABLE BEFORE INSERT OR UPDATE OR DELETE ON JSA_VERSION_PROMPT FOR EACH ROW
BEGIN JSA_ASSERT_VERSION_MUTABLE(COALESCE(:NEW.JSA_VERSION_ID,:OLD.JSA_VERSION_ID)); END;
/
CREATE OR REPLACE TRIGGER TRG_JSA_COVER_IMMUTABLE BEFORE INSERT OR UPDATE OR DELETE ON JSA_VERSION_PROMPT_COVERAGE FOR EACH ROW
BEGIN JSA_ASSERT_VERSION_MUTABLE(COALESCE(:NEW.JSA_VERSION_ID,:OLD.JSA_VERSION_ID)); END;
/
CREATE OR REPLACE TRIGGER TRG_JSA_TASK_IMMUTABLE BEFORE INSERT OR UPDATE OR DELETE ON JSA_VERSION_TASK FOR EACH ROW
BEGIN JSA_ASSERT_VERSION_MUTABLE(COALESCE(:NEW.JSA_VERSION_ID,:OLD.JSA_VERSION_ID)); END;
/
CREATE OR REPLACE TRIGGER TRG_JSA_HAZARD_IMMUTABLE BEFORE INSERT OR UPDATE OR DELETE ON JSA_VERSION_HAZARD FOR EACH ROW
BEGIN JSA_ASSERT_VERSION_MUTABLE(COALESCE(:NEW.JSA_VERSION_ID,:OLD.JSA_VERSION_ID)); END;
/
CREATE OR REPLACE TRIGGER TRG_JSA_CONTROL_IMUTABLE BEFORE INSERT OR UPDATE OR DELETE ON JSA_VERSION_CONTROL FOR EACH ROW
BEGIN JSA_ASSERT_VERSION_MUTABLE(COALESCE(:NEW.JSA_VERSION_ID,:OLD.JSA_VERSION_ID)); END;
/
CREATE OR REPLACE TRIGGER TRG_JSA_STEP_IMMUTABLE BEFORE INSERT OR UPDATE OR DELETE ON JSA_VERSION_BASIC_STEP FOR EACH ROW
BEGIN JSA_ASSERT_VERSION_MUTABLE(COALESCE(:NEW.JSA_VERSION_ID,:OLD.JSA_VERSION_ID)); END;
/
CREATE OR REPLACE TRIGGER TRG_JSA_PERF_IMMUTABLE BEFORE INSERT OR UPDATE OR DELETE ON JSA_VER_BASIC_STEP_PERFORMER FOR EACH ROW
BEGIN JSA_ASSERT_VERSION_MUTABLE(COALESCE(:NEW.JSA_VERSION_ID,:OLD.JSA_VERSION_ID)); END;
/
CREATE OR REPLACE TRIGGER TRG_JSA_SUP_IMMUTABLE BEFORE INSERT OR UPDATE OR DELETE ON JSA_VER_BASIC_STEP_SUPERVISOR FOR EACH ROW
BEGIN JSA_ASSERT_VERSION_MUTABLE(COALESCE(:NEW.JSA_VERSION_ID,:OLD.JSA_VERSION_ID)); END;
/
CREATE OR REPLACE TRIGGER TRG_JSA_TOOL_IMMUTABLE BEFORE INSERT OR UPDATE OR DELETE ON JSA_VER_BASIC_STEP_TOOL FOR EACH ROW
BEGIN JSA_ASSERT_VERSION_MUTABLE(COALESCE(:NEW.JSA_VERSION_ID,:OLD.JSA_VERSION_ID)); END;
/
CREATE OR REPLACE TRIGGER TRG_JSA_PROC_IMMUTABLE BEFORE INSERT OR UPDATE OR DELETE ON JSA_VERSION_PROCEDURE_REF FOR EACH ROW
BEGIN JSA_ASSERT_VERSION_MUTABLE(COALESCE(:NEW.JSA_VERSION_ID,:OLD.JSA_VERSION_ID)); END;
/
CREATE OR REPLACE TRIGGER TRG_JSA_ATTACH_IMMUTABLE BEFORE INSERT OR UPDATE OR DELETE ON JSA_VERSION_ATTACHMENT FOR EACH ROW
BEGIN JSA_ASSERT_VERSION_MUTABLE(COALESCE(:NEW.JSA_VERSION_ID,:OLD.JSA_VERSION_ID)); END;
/
