CREATE SEQUENCE SEQ_SYS_ACCESS_ADMIN_AUDIT START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;

ALTER TABLE JSA_WORKFLOW_TASK ADD (
  STEP_CODE_SNAPSHOT VARCHAR2(50 CHAR),
  STEP_NAME_SNAPSHOT VARCHAR2(200 CHAR),
  WF_ROLE_CODE_SNAPSHOT VARCHAR2(50 CHAR),
  ASSIGNEE_USERNAME_SNAPSHOT VARCHAR2(255 CHAR),
  ASSIGNEE_DISPLAY_SNAPSHOT VARCHAR2(255 CHAR)
);

UPDATE JSA_WORKFLOW_TASK T
SET (
  STEP_CODE_SNAPSHOT,
  STEP_NAME_SNAPSHOT,
  WF_ROLE_CODE_SNAPSHOT,
  ASSIGNEE_USERNAME_SNAPSHOT,
  ASSIGNEE_DISPLAY_SNAPSHOT
) = (
  SELECT S.STEP_CODE, S.STEP_NAME, S.WORKFLOW_ROLE_CODE, U.USERNAME, U.DISPLAY_NAME
  FROM JSA_WORKFLOW_STEP S
  JOIN SYS_USER U ON U.USER_ID = T.ASSIGNEE_USER_ID
  WHERE S.STEP_ID = T.STEP_ID
);

ALTER TABLE JSA_WORKFLOW_TASK MODIFY (
  STEP_CODE_SNAPSHOT NOT NULL,
  STEP_NAME_SNAPSHOT NOT NULL,
  WF_ROLE_CODE_SNAPSHOT NOT NULL,
  ASSIGNEE_USERNAME_SNAPSHOT NOT NULL,
  ASSIGNEE_DISPLAY_SNAPSHOT NOT NULL
);

ALTER TABLE JSA_WORKFLOW_ACTION ADD (
  STEP_CODE_SNAPSHOT VARCHAR2(50 CHAR),
  STEP_NAME_SNAPSHOT VARCHAR2(200 CHAR),
  WF_ROLE_CODE_SNAPSHOT VARCHAR2(50 CHAR),
  ACTOR_DISPLAY_NAME_SNAPSHOT VARCHAR2(255 CHAR)
);

UPDATE JSA_WORKFLOW_ACTION A
SET (
  STEP_CODE_SNAPSHOT,
  STEP_NAME_SNAPSHOT,
  WF_ROLE_CODE_SNAPSHOT,
  ACTOR_DISPLAY_NAME_SNAPSHOT
) = (
  SELECT T.STEP_CODE_SNAPSHOT, T.STEP_NAME_SNAPSHOT, T.WF_ROLE_CODE_SNAPSHOT, U.DISPLAY_NAME
  FROM SYS_USER U
  LEFT JOIN JSA_WORKFLOW_TASK T ON T.WORKFLOW_TASK_ID = A.WORKFLOW_TASK_ID
  WHERE U.USER_ID = A.ACTOR_USER_ID
);

UPDATE JSA_WORKFLOW_ACTION
SET ACTOR_DISPLAY_NAME_SNAPSHOT = ACTOR_USERNAME
WHERE ACTOR_DISPLAY_NAME_SNAPSHOT IS NULL;

ALTER TABLE JSA_WORKFLOW_ACTION MODIFY ACTOR_DISPLAY_NAME_SNAPSHOT NOT NULL;

CREATE TABLE SYS_ACCESS_ADMIN_AUDIT (
  AUDIT_EVENT_ID NUMBER(19) NOT NULL,
  ACTION_CODE VARCHAR2(100 CHAR) NOT NULL,
  TARGET_ENTITY_TYPE VARCHAR2(100 CHAR) NOT NULL,
  TARGET_ENTITY_ID NUMBER(19),
  TARGET_USERNAME_SNAPSHOT VARCHAR2(255 CHAR),
  ACTOR_USER_ID NUMBER(19) NOT NULL,
  ACTOR_USERNAME_SNAPSHOT VARCHAR2(255 CHAR) NOT NULL,
  ACTOR_DISPLAY_SNAPSHOT VARCHAR2(255 CHAR) NOT NULL,
  SITE_ID NUMBER(19),
  RIG_ID NUMBER(19),
  DEPARTMENT_ID NUMBER(19),
  BEFORE_STATE CLOB,
  AFTER_STATE CLOB,
  REASON_TEXT VARCHAR2(2000 CHAR),
  CORRELATION_ID VARCHAR2(100 CHAR) NOT NULL,
  OCCURRED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_SITE_ID NUMBER(19) NOT NULL,
  CONSTRAINT PK_SYS_ACCESS_ADMIN_AUDIT PRIMARY KEY (AUDIT_EVENT_ID),
  CONSTRAINT FK_SYS_ACCESS_AUDIT_ACTOR FOREIGN KEY (ACTOR_USER_ID) REFERENCES SYS_USER(USER_ID),
  CONSTRAINT FK_SYS_ACCESS_AUDIT_SITE FOREIGN KEY (SITE_ID) REFERENCES SYS_SITE(SITE_ID),
  CONSTRAINT FK_SYS_ACCESS_AUDIT_RIG FOREIGN KEY (RIG_ID,SITE_ID) REFERENCES SYS_RIG(RIG_ID,SITE_ID),
  CONSTRAINT FK_SYS_ACCESS_AUDIT_DEPT FOREIGN KEY (DEPARTMENT_ID,SITE_ID) REFERENCES SYS_DEPARTMENT(DEPARTMENT_ID,SITE_ID),
  CONSTRAINT FK_SYS_ACCESS_AUDIT_CREATED FOREIGN KEY (CREATED_SITE_ID) REFERENCES SYS_SITE(SITE_ID),
  CONSTRAINT CHK_SYS_ACCESS_AUDIT_SCOPE CHECK (
    (RIG_ID IS NULL OR SITE_ID IS NOT NULL)
    AND (DEPARTMENT_ID IS NULL OR SITE_ID IS NOT NULL)
  ),
  CONSTRAINT CHK_SYS_ACCESS_AUDIT_BEFORE CHECK (BEFORE_STATE IS NULL OR BEFORE_STATE IS JSON),
  CONSTRAINT CHK_SYS_ACCESS_AUDIT_AFTER CHECK (AFTER_STATE IS NULL OR AFTER_STATE IS JSON)
);

CREATE INDEX IX_SYS_ACCESS_AUDIT_TIME ON SYS_ACCESS_ADMIN_AUDIT(OCCURRED_AT,AUDIT_EVENT_ID);
CREATE INDEX IX_SYS_ACCESS_AUDIT_ACTOR ON SYS_ACCESS_ADMIN_AUDIT(ACTOR_USER_ID,OCCURRED_AT);
CREATE INDEX IX_SYS_ACCESS_AUDIT_TARGET ON SYS_ACCESS_ADMIN_AUDIT(TARGET_ENTITY_TYPE,TARGET_ENTITY_ID,OCCURRED_AT);
CREATE INDEX IX_SYS_ACCESS_AUDIT_SCOPE ON SYS_ACCESS_ADMIN_AUDIT(SITE_ID,RIG_ID,DEPARTMENT_ID,OCCURRED_AT);

/
CREATE OR REPLACE TRIGGER TRG_SYS_ACCESS_AUDIT_IMMUTABLE
BEFORE UPDATE OR DELETE ON SYS_ACCESS_ADMIN_AUDIT
BEGIN
  RAISE_APPLICATION_ERROR(-20051,'Access administration audit is immutable');
END;
/
