DECLARE
  V_DUPLICATE_HAZARDS NUMBER;
BEGIN
  SELECT COUNT(*)
  INTO V_DUPLICATE_HAZARDS
  FROM (
    SELECT VERSION_HAZARD_ID
    FROM JSA_VERSION_CONTROL
    WHERE IS_ACTIVE='Y'
    GROUP BY VERSION_HAZARD_ID
    HAVING COUNT(*)>1
  );

  IF V_DUPLICATE_HAZARDS>0 THEN
    RAISE_APPLICATION_ERROR(
      -20061,
      'Cannot enforce Hazard-Control 1:1 while a Hazard has multiple active Controls'
    );
  END IF;
END;
/

CREATE UNIQUE INDEX UX_JSA_VER_CTL_ACTIVE_HAZ ON JSA_VERSION_CONTROL (
  CASE WHEN IS_ACTIVE='Y' THEN VERSION_HAZARD_ID END
);
