DECLARE
  V_MISMATCHED_HAZARDS NUMBER;
BEGIN
  SELECT COUNT(*)
  INTO V_MISMATCHED_HAZARDS
  FROM JSA_VERSION_HAZARD
  WHERE (INITIAL_SEVERITY_ID IS NULL AND RESIDUAL_SEVERITY_ID IS NOT NULL)
     OR (INITIAL_SEVERITY_ID IS NOT NULL AND RESIDUAL_SEVERITY_ID IS NULL)
     OR INITIAL_SEVERITY_ID<>RESIDUAL_SEVERITY_ID;

  IF V_MISMATCHED_HAZARDS>0 THEN
    RAISE_APPLICATION_ERROR(
      -20062,
      'Cannot enforce matching Severity while Initial and Residual Severity differ'
    );
  END IF;
END;
/

ALTER TABLE JSA_VERSION_HAZARD ADD CONSTRAINT CHK_JSA_HAZ_RES_SEV_MATCH CHECK (
  (INITIAL_SEVERITY_ID IS NULL AND RESIDUAL_SEVERITY_ID IS NULL)
  OR INITIAL_SEVERITY_ID=RESIDUAL_SEVERITY_ID
);
