DECLARE
  V_ACTIVE_ENGLISH NUMBER;
  V_NON_ENGLISH_VERSIONS NUMBER;
  V_PUBLISHED_WITHOUT_LANGUAGE NUMBER;
BEGIN
  SELECT COUNT(*)
  INTO V_ACTIVE_ENGLISH
  FROM SYS_LANGUAGE
  WHERE UPPER(LANGUAGE_CODE)='EN'
    AND IS_ACTIVE='Y';

  IF V_ACTIVE_ENGLISH<>1 THEN
    RAISE_APPLICATION_ERROR(
      -20063,
      'Exactly one active English language with code EN is required'
    );
  END IF;

  SELECT COUNT(*)
  INTO V_NON_ENGLISH_VERSIONS
  FROM JSA_VERSION V
  JOIN SYS_LANGUAGE L ON L.LANGUAGE_ID=V.LANGUAGE_ID
  WHERE UPPER(L.LANGUAGE_CODE)<>'EN';

  IF V_NON_ENGLISH_VERSIONS>0 THEN
    RAISE_APPLICATION_ERROR(
      -20064,
      'Existing source JSA Versions must use English before applying this migration'
    );
  END IF;

  SELECT COUNT(*)
  INTO V_PUBLISHED_WITHOUT_LANGUAGE
  FROM JSA_VERSION
  WHERE VERSION_STATUS='PUBLISHED'
    AND LANGUAGE_ID IS NULL;

  IF V_PUBLISHED_WITHOUT_LANGUAGE>0 THEN
    RAISE_APPLICATION_ERROR(
      -20065,
      'Published JSA Versions without language require manual immutable-data remediation'
    );
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_JSA_VERSION_ENGLISH
BEFORE INSERT OR UPDATE OF LANGUAGE_ID ON JSA_VERSION
FOR EACH ROW
DECLARE
  V_ENGLISH_COUNT NUMBER;
BEGIN
  SELECT COUNT(*)
  INTO V_ENGLISH_COUNT
  FROM SYS_LANGUAGE
  WHERE LANGUAGE_ID=:NEW.LANGUAGE_ID
    AND UPPER(LANGUAGE_CODE)='EN'
    AND IS_ACTIVE='Y';

  IF V_ENGLISH_COUNT<>1 THEN
    RAISE_APPLICATION_ERROR(
      -20066,
      'Source JSA Version language must be the active English language'
    );
  END IF;
END;
/

UPDATE JSA_VERSION
SET LANGUAGE_ID=(
  SELECT LANGUAGE_ID
  FROM SYS_LANGUAGE
  WHERE UPPER(LANGUAGE_CODE)='EN'
    AND IS_ACTIVE='Y'
)
WHERE LANGUAGE_ID IS NULL;
/

DECLARE
  V_JOB_TYPE_NULLABLE USER_TAB_COLUMNS.NULLABLE%TYPE;
  V_LANGUAGE_NULLABLE USER_TAB_COLUMNS.NULLABLE%TYPE;
BEGIN
  SELECT NULLABLE
  INTO V_JOB_TYPE_NULLABLE
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME='JSA_VERSION'
    AND COLUMN_NAME='JOB_TYPE_ID';

  SELECT NULLABLE
  INTO V_LANGUAGE_NULLABLE
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME='JSA_VERSION'
    AND COLUMN_NAME='LANGUAGE_ID';

  IF V_JOB_TYPE_NULLABLE='N' THEN
    EXECUTE IMMEDIATE 'ALTER TABLE JSA_VERSION MODIFY (JOB_TYPE_ID NULL)';
  END IF;
  IF V_LANGUAGE_NULLABLE='Y' THEN
    EXECUTE IMMEDIATE 'ALTER TABLE JSA_VERSION MODIFY (LANGUAGE_ID NOT NULL)';
  END IF;
END;
/
