DECLARE
  V_COLUMN_COUNT NUMBER;
BEGIN
  SELECT COUNT(*)
  INTO V_COLUMN_COUNT
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME='JSA_MASTER'
    AND COLUMN_NAME='NUMBER_STATUS';

  IF V_COLUMN_COUNT=0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE JSA_MASTER ADD (
        NUMBER_STATUS VARCHAR2(20 CHAR) DEFAULT 'TEMPORARY' NOT NULL,
        CONSTRAINT CHK_JSA_MASTER_NUM_STATUS
          CHECK (NUMBER_STATUS IN ('TEMPORARY','OFFICIAL'))
      )
    ]';
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_JSA_OFFICIAL_NUM_IMMUTABLE
BEFORE UPDATE OF JSA_NUMBER,NUMBER_SCOPE_KEY,NUMBER_STATUS ON JSA_MASTER
FOR EACH ROW
BEGIN
  IF :OLD.NUMBER_STATUS='OFFICIAL'
     AND (
       :NEW.JSA_NUMBER<>:OLD.JSA_NUMBER
       OR :NEW.NUMBER_SCOPE_KEY<>:OLD.NUMBER_SCOPE_KEY
       OR :NEW.NUMBER_STATUS<>:OLD.NUMBER_STATUS
     )
  THEN
    RAISE_APPLICATION_ERROR(-20068,'Official JSA number is immutable');
  END IF;
END;
/

UPDATE JSA_MASTER
SET NUMBER_STATUS='OFFICIAL'
WHERE LIFECYCLE_STATUS='PUBLISHED'
  AND NUMBER_STATUS<>'OFFICIAL';
/

DECLARE
  V_TABLE_COUNT NUMBER;
BEGIN
  SELECT COUNT(*)
  INTO V_TABLE_COUNT
  FROM USER_TABLES
  WHERE TABLE_NAME='JSA_NUMBER_COUNTER';

  IF V_TABLE_COUNT=0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE JSA_NUMBER_COUNTER (
        SITE_ID NUMBER(19) NOT NULL,
        RIG_ID NUMBER(19) NOT NULL,
        DEPARTMENT_ID NUMBER(19) NOT NULL,
        LAST_NUMBER NUMBER(4) DEFAULT 0 NOT NULL,
        CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
        UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
        ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
        CONSTRAINT PK_JSA_NUMBER_COUNTER PRIMARY KEY (RIG_ID,DEPARTMENT_ID),
        CONSTRAINT FK_JSA_NUM_COUNTER_RIG FOREIGN KEY (RIG_ID,SITE_ID)
          REFERENCES SYS_RIG(RIG_ID,SITE_ID),
        CONSTRAINT FK_JSA_NUM_COUNTER_DEPT_SITE FOREIGN KEY (DEPARTMENT_ID,SITE_ID)
          REFERENCES SYS_DEPARTMENT(DEPARTMENT_ID,SITE_ID),
        CONSTRAINT FK_JSA_NUM_COUNTER_DEPT_RIG FOREIGN KEY (DEPARTMENT_ID,RIG_ID)
          REFERENCES SYS_DEPARTMENT(DEPARTMENT_ID,RIG_ID),
        CONSTRAINT CHK_JSA_NUM_COUNTER_VALUE CHECK (LAST_NUMBER BETWEEN 0 AND 9999),
        CONSTRAINT CHK_JSA_NUM_COUNTER_ROW_VER CHECK (ROW_VERSION>=1)
      )
    ]';
  END IF;
END;
/
