CREATE SEQUENCE SEQ_JSA_ATTACHMENT_FOLDER START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_ATTACHMENT_ASSET START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;
CREATE SEQUENCE SEQ_JSA_ATTACHMENT_VERSION START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;

CREATE TABLE JSA_ATTACHMENT_FOLDER (
  ATTACHMENT_FOLDER_ID NUMBER(19) NOT NULL,
  SITE_ID NUMBER(19) NOT NULL,
  RIG_ID NUMBER(19) NOT NULL,
  DEPARTMENT_ID NUMBER(19) NOT NULL,
  PARENT_FOLDER_ID NUMBER(19),
  FOLDER_NAME VARCHAR2(200 CHAR) NOT NULL,
  IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  CREATED_SITE_ID NUMBER(19) NOT NULL,
  UPDATED_SITE_ID NUMBER(19) NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
  UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
  ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JSA_ATTACHMENT_FOLDER PRIMARY KEY (ATTACHMENT_FOLDER_ID),
  CONSTRAINT UK_JSA_ATTACH_FOLDER_SCOPE UNIQUE (ATTACHMENT_FOLDER_ID,SITE_ID,RIG_ID,DEPARTMENT_ID),
  CONSTRAINT FK_JSA_ATTACH_FOLDER_SITE FOREIGN KEY (SITE_ID) REFERENCES SYS_SITE(SITE_ID),
  CONSTRAINT FK_JSA_ATTACH_FOLDER_RIG FOREIGN KEY (RIG_ID,SITE_ID) REFERENCES SYS_RIG(RIG_ID,SITE_ID),
  CONSTRAINT FK_JSA_ATTACH_FOLDER_DEPT FOREIGN KEY (DEPARTMENT_ID,SITE_ID) REFERENCES SYS_DEPARTMENT(DEPARTMENT_ID,SITE_ID),
  CONSTRAINT FK_JSA_ATTACH_FOLDER_DEPT_RIG FOREIGN KEY (DEPARTMENT_ID,RIG_ID) REFERENCES SYS_DEPARTMENT(DEPARTMENT_ID,RIG_ID),
  CONSTRAINT FK_JSA_ATTACH_FOLDER_PARENT FOREIGN KEY (PARENT_FOLDER_ID,SITE_ID,RIG_ID,DEPARTMENT_ID)
    REFERENCES JSA_ATTACHMENT_FOLDER(ATTACHMENT_FOLDER_ID,SITE_ID,RIG_ID,DEPARTMENT_ID),
  CONSTRAINT FK_JSA_ATTACH_FOLDER_CREATED_SITE FOREIGN KEY (CREATED_SITE_ID) REFERENCES SYS_SITE(SITE_ID),
  CONSTRAINT FK_JSA_ATTACH_FOLDER_UPDATED_SITE FOREIGN KEY (UPDATED_SITE_ID) REFERENCES SYS_SITE(SITE_ID),
  CONSTRAINT CHK_JSA_ATTACH_FOLDER_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
  CONSTRAINT CHK_JSA_ATTACH_FOLDER_NAME CHECK (TRIM(FOLDER_NAME) IS NOT NULL),
  CONSTRAINT CHK_JSA_ATTACH_FOLDER_RV CHECK (ROW_VERSION>=1)
);

CREATE UNIQUE INDEX UX_JSA_ATTACH_FOLDER_NAME ON JSA_ATTACHMENT_FOLDER(
  SITE_ID,RIG_ID,DEPARTMENT_ID,
  CASE WHEN IS_ACTIVE='Y' THEN NVL(PARENT_FOLDER_ID,-1) END,
  CASE WHEN IS_ACTIVE='Y' THEN UPPER(FOLDER_NAME) END
);

CREATE TABLE JSA_ATTACHMENT_ASSET (
  ATTACHMENT_ASSET_ID NUMBER(19) NOT NULL,
  ATTACHMENT_FOLDER_ID NUMBER(19) NOT NULL,
  ASSET_NAME VARCHAR2(500 CHAR) NOT NULL,
  DESCRIPTION VARCHAR2(1000 CHAR),
  CURRENT_VERSION_ID NUMBER(19),
  IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  CREATED_SITE_ID NUMBER(19) NOT NULL,
  UPDATED_SITE_ID NUMBER(19) NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
  UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
  ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JSA_ATTACHMENT_ASSET PRIMARY KEY (ATTACHMENT_ASSET_ID),
  CONSTRAINT FK_JSA_ATTACH_ASSET_FOLDER FOREIGN KEY (ATTACHMENT_FOLDER_ID) REFERENCES JSA_ATTACHMENT_FOLDER(ATTACHMENT_FOLDER_ID),
  CONSTRAINT FK_JSA_ATTACH_ASSET_CREATED_SITE FOREIGN KEY (CREATED_SITE_ID) REFERENCES SYS_SITE(SITE_ID),
  CONSTRAINT FK_JSA_ATTACH_ASSET_UPDATED_SITE FOREIGN KEY (UPDATED_SITE_ID) REFERENCES SYS_SITE(SITE_ID),
  CONSTRAINT CHK_JSA_ATTACH_ASSET_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
  CONSTRAINT CHK_JSA_ATTACH_ASSET_NAME CHECK (TRIM(ASSET_NAME) IS NOT NULL),
  CONSTRAINT CHK_JSA_ATTACH_ASSET_RV CHECK (ROW_VERSION>=1)
);

CREATE TABLE JSA_ATTACHMENT_ASSET_VERSION (
  ATTACHMENT_ASSET_VERSION_ID NUMBER(19) NOT NULL,
  ATTACHMENT_ASSET_ID NUMBER(19) NOT NULL,
  VERSION_NUMBER NUMBER(10) NOT NULL,
  ORIGINAL_FILE_NAME VARCHAR2(500 CHAR) NOT NULL,
  CONTENT_TYPE VARCHAR2(200 CHAR) NOT NULL,
  FILE_SIZE NUMBER(19) NOT NULL,
  CONTENT_SHA256 VARCHAR2(64 CHAR) NOT NULL,
  STORAGE_KEY VARCHAR2(1000 CHAR) NOT NULL,
  STORAGE_STATUS VARCHAR2(20 CHAR) DEFAULT 'STORED' NOT NULL,
  CREATED_SITE_ID NUMBER(19) NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
  CONSTRAINT PK_JSA_ATTACHMENT_ASSET_VER PRIMARY KEY (ATTACHMENT_ASSET_VERSION_ID),
  CONSTRAINT UK_JSA_ATTACH_ASSET_VER UNIQUE (ATTACHMENT_ASSET_ID,VERSION_NUMBER),
  CONSTRAINT UK_JSA_ATTACH_STORAGE_KEY UNIQUE (STORAGE_KEY),
  CONSTRAINT FK_JSA_ATTACH_VER_ASSET FOREIGN KEY (ATTACHMENT_ASSET_ID) REFERENCES JSA_ATTACHMENT_ASSET(ATTACHMENT_ASSET_ID),
  CONSTRAINT FK_JSA_ATTACH_VER_CREATED_SITE FOREIGN KEY (CREATED_SITE_ID) REFERENCES SYS_SITE(SITE_ID),
  CONSTRAINT CHK_JSA_ATTACH_VER_NUM CHECK (VERSION_NUMBER>=1),
  CONSTRAINT CHK_JSA_ATTACH_VER_SIZE CHECK (FILE_SIZE>=1),
  CONSTRAINT CHK_JSA_ATTACH_VER_SHA CHECK (REGEXP_LIKE(CONTENT_SHA256,'^[0-9a-f]{64}$')),
  CONSTRAINT CHK_JSA_ATTACH_VER_STATUS CHECK (STORAGE_STATUS IN ('STORED','FAILED'))
);

ALTER TABLE JSA_ATTACHMENT_ASSET ADD CONSTRAINT FK_JSA_ATTACH_ASSET_CURRENT
  FOREIGN KEY (CURRENT_VERSION_ID) REFERENCES JSA_ATTACHMENT_ASSET_VERSION(ATTACHMENT_ASSET_VERSION_ID);

ALTER TABLE JSA_VERSION_ATTACHMENT ADD (
  LIBRARY_ASSET_VERSION_ID NUMBER(19),
  CONTENT_SHA256 VARCHAR2(64 CHAR)
);
ALTER TABLE JSA_VERSION_ATTACHMENT ADD CONSTRAINT FK_JSA_VER_ATTACH_LIBRARY
  FOREIGN KEY (LIBRARY_ASSET_VERSION_ID) REFERENCES JSA_ATTACHMENT_ASSET_VERSION(ATTACHMENT_ASSET_VERSION_ID);

CREATE INDEX IX_JSA_ATTACH_FOLDER_SCOPE ON JSA_ATTACHMENT_FOLDER(SITE_ID,RIG_ID,DEPARTMENT_ID,PARENT_FOLDER_ID,IS_ACTIVE);
CREATE INDEX IX_JSA_ATTACH_ASSET_FOLDER ON JSA_ATTACHMENT_ASSET(ATTACHMENT_FOLDER_ID,IS_ACTIVE);
CREATE INDEX IX_JSA_VER_ATTACH_LIBRARY ON JSA_VERSION_ATTACHMENT(LIBRARY_ASSET_VERSION_ID);

INSERT INTO SYS_PERMISSION
  (PERMISSION_ID,PERMISSION_CODE,PERMISSION_NAME,DESCRIPTION,PERMISSION_GROUP,CREATED_BY,UPDATED_BY)
SELECT SEQ_SYS_PERMISSION.NEXTVAL,'ATTACHMENT_LIBRARY_ADMIN','Administer attachment library',
       'Manage scoped attachment folders and versioned files','JSA','MIGRATION_012','MIGRATION_012'
FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM SYS_PERMISSION WHERE PERMISSION_CODE='ATTACHMENT_LIBRARY_ADMIN');

INSERT INTO SYS_ROLE_PERMISSION
  (ROLE_PERMISSION_ID,ROLE_ID,PERMISSION_ID,CREATED_BY,UPDATED_BY)
SELECT SEQ_SYS_ROLE_PERMISSION.NEXTVAL,R.ROLE_ID,P.PERMISSION_ID,'MIGRATION_012','MIGRATION_012'
FROM SYS_ROLE R
JOIN SYS_PERMISSION P ON P.PERMISSION_CODE='ATTACHMENT_LIBRARY_ADMIN'
WHERE R.ROLE_CODE='SYSTEM_ADMIN'
  AND R.IS_ACTIVE='Y' AND P.IS_ACTIVE='Y'
  AND NOT EXISTS (
    SELECT 1 FROM SYS_ROLE_PERMISSION RP
    WHERE RP.ROLE_ID=R.ROLE_ID AND RP.PERMISSION_ID=P.PERMISSION_ID AND RP.IS_ACTIVE='Y'
  );
