ALTER TABLE JSA_MASTER ADD (
  CHECKED_OUT_BY_USER_ID NUMBER(19),
  CHECKED_OUT_BY_USERNAME VARCHAR2(255 CHAR),
  CHECKED_OUT_BY_DISPLAY_NAME VARCHAR2(255 CHAR),
  CHECKED_OUT_AT TIMESTAMP(6),
  CONSTRAINT FK_JSA_MASTER_CHECKOUT_USER FOREIGN KEY (CHECKED_OUT_BY_USER_ID) REFERENCES SYS_USER(USER_ID),
  CONSTRAINT CHK_JSA_MASTER_CHECKOUT CHECK (
    (WORKING_VERSION_ID IS NULL AND CHECKED_OUT_BY_USER_ID IS NULL AND CHECKED_OUT_BY_USERNAME IS NULL
      AND CHECKED_OUT_BY_DISPLAY_NAME IS NULL AND CHECKED_OUT_AT IS NULL)
    OR
    (WORKING_VERSION_ID IS NOT NULL AND CHECKED_OUT_BY_USER_ID IS NOT NULL
      AND CHECKED_OUT_BY_USERNAME IS NOT NULL AND CHECKED_OUT_AT IS NOT NULL)
    OR
    (CURRENT_VERSION_ID IS NULL AND WORKING_VERSION_ID IS NOT NULL AND CHECKED_OUT_BY_USER_ID IS NULL
      AND CHECKED_OUT_BY_USERNAME IS NULL AND CHECKED_OUT_BY_DISPLAY_NAME IS NULL AND CHECKED_OUT_AT IS NULL)
  )
);

CREATE INDEX IX_JSA_MASTER_CURRENT_WORKING
  ON JSA_MASTER(CURRENT_VERSION_ID,WORKING_VERSION_ID,OWNER_SITE_ID,RIG_ID,DEPARTMENT_ID);
CREATE INDEX IX_JSA_VERSION_BASE ON JSA_VERSION(BASE_VERSION_ID,JSA_ID,VERSION_STATUS);

ALTER TABLE JSA_VERSION DROP CONSTRAINT CHK_JSA_VER_PUBLISHED;
ALTER TABLE JSA_VERSION DROP CONSTRAINT CHK_JSA_VERSION_STATUS;
ALTER TABLE JSA_VERSION ADD CONSTRAINT CHK_JSA_VERSION_STATUS CHECK (
  VERSION_STATUS IN (
    'DRAFT','DEPARTMENT_HEAD_REVIEW','STC_REVIEW','OIM_REVIEW','RIG_MANAGER_REVIEW',
    'RETURNED','REJECTED','PUBLISHED','SUPERSEDED','CANCELLED'
  )
);
ALTER TABLE JSA_VERSION ADD CONSTRAINT CHK_JSA_VER_PUBLISHED CHECK (
  (VERSION_STATUS IN ('PUBLISHED','SUPERSEDED')
    AND PUBLISHED_AT IS NOT NULL AND PUBLISHED_BY_USER_ID IS NOT NULL AND PUBLISHED_BY_USERNAME IS NOT NULL)
  OR
  (VERSION_STATUS NOT IN ('PUBLISHED','SUPERSEDED')
    AND PUBLISHED_AT IS NULL AND PUBLISHED_BY_USER_ID IS NULL AND PUBLISHED_BY_USERNAME IS NULL)
);
/

CREATE OR REPLACE PROCEDURE JSA_ASSERT_VERSION_MUTABLE(P_VERSION_ID NUMBER) AS
  V_STATUS JSA_VERSION.VERSION_STATUS%TYPE;
BEGIN
  SELECT VERSION_STATUS INTO V_STATUS FROM JSA_VERSION WHERE JSA_VERSION_ID=P_VERSION_ID;
  IF V_STATUS IN ('PUBLISHED','SUPERSEDED') THEN
    RAISE_APPLICATION_ERROR(-20041,'Published or Superseded JSA Version is immutable');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_JSA_VER_IMMUTABLE
BEFORE UPDATE OR DELETE ON JSA_VERSION
FOR EACH ROW
BEGIN
  IF DELETING AND :OLD.VERSION_STATUS IN ('PUBLISHED','SUPERSEDED') THEN
    RAISE_APPLICATION_ERROR(-20041,'Published or Superseded JSA Version is immutable');
  END IF;

  IF UPDATING AND :OLD.VERSION_STATUS='SUPERSEDED' THEN
    RAISE_APPLICATION_ERROR(-20041,'Superseded JSA Version is immutable');
  END IF;

  IF UPDATING AND :OLD.VERSION_STATUS='PUBLISHED' THEN
    IF :NEW.VERSION_STATUS<>'SUPERSEDED'
       OR :NEW.JSA_ID<>:OLD.JSA_ID
       OR :NEW.VERSION_NUMBER<>:OLD.VERSION_NUMBER
       OR NVL(:NEW.VERSION_LABEL,CHR(0))<>NVL(:OLD.VERSION_LABEL,CHR(0))
       OR NVL(:NEW.BASE_VERSION_ID,-1)<>NVL(:OLD.BASE_VERSION_ID,-1)
       OR :NEW.OWNER_SITE_ID<>:OLD.OWNER_SITE_ID
       OR :NEW.RIG_ID<>:OLD.RIG_ID
       OR :NEW.DEPARTMENT_ID<>:OLD.DEPARTMENT_ID
       OR NVL(:NEW.JOB_TYPE_ID,-1)<>NVL(:OLD.JOB_TYPE_ID,-1)
       OR :NEW.MATRIX_VERSION_ID<>:OLD.MATRIX_VERSION_ID
       OR :NEW.LANGUAGE_ID<>:OLD.LANGUAGE_ID
       OR NVL(:NEW.JOB_TITLE,CHR(0))<>NVL(:OLD.JOB_TITLE,CHR(0))
       OR (:NEW.JOB_DESCRIPTION IS NULL AND :OLD.JOB_DESCRIPTION IS NOT NULL)
       OR (:NEW.JOB_DESCRIPTION IS NOT NULL AND :OLD.JOB_DESCRIPTION IS NULL)
       OR (:NEW.JOB_DESCRIPTION IS NOT NULL AND :OLD.JOB_DESCRIPTION IS NOT NULL
           AND DBMS_LOB.COMPARE(:NEW.JOB_DESCRIPTION,:OLD.JOB_DESCRIPTION)<>0)
       OR NVL(:NEW.LOCATION_TEXT,CHR(0))<>NVL(:OLD.LOCATION_TEXT,CHR(0))
       OR NVL(:NEW.PERSONNEL_TEXT,CHR(0))<>NVL(:OLD.PERSONNEL_TEXT,CHR(0))
       OR :NEW.PTW_REQUIRED_FLAG<>:OLD.PTW_REQUIRED_FLAG
       OR NVL(:NEW.PTW_REFERENCE,CHR(0))<>NVL(:OLD.PTW_REFERENCE,CHR(0))
       OR :NEW.PUBLISHED_AT<>:OLD.PUBLISHED_AT
       OR :NEW.PUBLISHED_BY_USER_ID<>:OLD.PUBLISHED_BY_USER_ID
       OR :NEW.PUBLISHED_BY_USERNAME<>:OLD.PUBLISHED_BY_USERNAME
    THEN
      RAISE_APPLICATION_ERROR(-20041,'Published JSA Version is immutable except for superseding');
    END IF;
  END IF;
END;
/
