CREATE SEQUENCE SEQ_JSA_USER_FAVORITE START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;

CREATE TABLE JSA_USER_FAVORITE (
  FAVORITE_ID NUMBER(19) NOT NULL,
  USER_ID NUMBER(19) NOT NULL,
  JSA_ID NUMBER(19) NOT NULL,
  IS_ACTIVE CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
  FAVORITED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  UNFAVORITED_AT TIMESTAMP(6),
  CREATED_SITE_ID NUMBER(19) NOT NULL,
  UPDATED_SITE_ID NUMBER(19) NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
  UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR2(255 CHAR) NOT NULL,
  ROW_VERSION NUMBER(19) DEFAULT 1 NOT NULL,
  CONSTRAINT PK_JSA_USER_FAVORITE PRIMARY KEY (FAVORITE_ID),
  CONSTRAINT UK_JSA_USER_FAVORITE UNIQUE (USER_ID,JSA_ID),
  CONSTRAINT FK_JSA_FAVORITE_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USER(USER_ID),
  CONSTRAINT FK_JSA_FAVORITE_MASTER FOREIGN KEY (JSA_ID) REFERENCES JSA_MASTER(JSA_ID),
  CONSTRAINT FK_JSA_FAVORITE_CREATED_SITE FOREIGN KEY (CREATED_SITE_ID) REFERENCES SYS_SITE(SITE_ID),
  CONSTRAINT FK_JSA_FAVORITE_UPDATED_SITE FOREIGN KEY (UPDATED_SITE_ID) REFERENCES SYS_SITE(SITE_ID),
  CONSTRAINT CHK_JSA_FAVORITE_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
  CONSTRAINT CHK_JSA_FAVORITE_TIMES CHECK (
    (IS_ACTIVE='Y' AND UNFAVORITED_AT IS NULL)
    OR (IS_ACTIVE='N' AND UNFAVORITED_AT IS NOT NULL)
  ),
  CONSTRAINT CHK_JSA_FAVORITE_RV CHECK (ROW_VERSION>=1)
);

CREATE INDEX IX_JSA_FAVORITE_USER_ACTIVE
  ON JSA_USER_FAVORITE(USER_ID,IS_ACTIVE,UPDATED_AT DESC,JSA_ID);
CREATE INDEX IX_JSA_FAVORITE_MASTER_ACTIVE
  ON JSA_USER_FAVORITE(JSA_ID,IS_ACTIVE,USER_ID);
CREATE INDEX IX_JSA_VERSION_BROWSE_STATE
  ON JSA_VERSION(VERSION_STATUS,MATRIX_VERSION_ID,UPDATED_AT DESC,JSA_ID);
CREATE INDEX IX_JSA_VERSION_BROWSE_ACTORS
  ON JSA_VERSION(PUBLISHED_BY_USER_ID,VERSION_STATUS,JSA_ID);
