CREATE SEQUENCE SEQ_JSA_COPY_PROVENANCE START WITH 1 INCREMENT BY 1 NOCYCLE CACHE 100;

CREATE TABLE JSA_COPY_PROVENANCE (
  COPY_PROVENANCE_ID NUMBER(19) NOT NULL,
  DESTINATION_JSA_ID NUMBER(19) NOT NULL,
  DESTINATION_VERSION_ID NUMBER(19) NOT NULL,
  SOURCE_JSA_ID NUMBER(19) NOT NULL,
  SOURCE_VERSION_ID NUMBER(19) NOT NULL,
  SOURCE_SITE_ID NUMBER(19) NOT NULL,
  SOURCE_RIG_ID NUMBER(19) NOT NULL,
  COPY_REASON VARCHAR2(1000 CHAR) NOT NULL,
  COPIED_BY_USER_ID NUMBER(19) NOT NULL,
  COPIED_BY_USERNAME VARCHAR2(255 CHAR) NOT NULL,
  COPIED_BY_DISPLAY_NAME VARCHAR2(255 CHAR),
  COPIED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_SITE_ID NUMBER(19) NOT NULL,
  REQUEST_KEY VARCHAR2(128 CHAR) NOT NULL,
  REQUEST_HASH VARCHAR2(64 CHAR) NOT NULL,
  CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY VARCHAR2(255 CHAR) NOT NULL,
  CONSTRAINT PK_JSA_COPY_PROVENANCE PRIMARY KEY (COPY_PROVENANCE_ID),
  CONSTRAINT UK_JSA_COPY_DESTINATION UNIQUE (DESTINATION_JSA_ID),
  CONSTRAINT UK_JSA_COPY_REQUEST UNIQUE (COPIED_BY_USER_ID,REQUEST_KEY),
  CONSTRAINT FK_JSA_COPY_DESTINATION FOREIGN KEY (DESTINATION_JSA_ID)
    REFERENCES JSA_MASTER(JSA_ID),
  CONSTRAINT FK_JSA_COPY_DEST_VERSION FOREIGN KEY (DESTINATION_VERSION_ID,DESTINATION_JSA_ID)
    REFERENCES JSA_VERSION(JSA_VERSION_ID,JSA_ID),
  CONSTRAINT FK_JSA_COPY_SOURCE FOREIGN KEY (SOURCE_JSA_ID)
    REFERENCES JSA_MASTER(JSA_ID),
  CONSTRAINT FK_JSA_COPY_SOURCE_VERSION FOREIGN KEY (SOURCE_VERSION_ID,SOURCE_JSA_ID)
    REFERENCES JSA_VERSION(JSA_VERSION_ID,JSA_ID),
  CONSTRAINT FK_JSA_COPY_SOURCE_RIG FOREIGN KEY (SOURCE_RIG_ID,SOURCE_SITE_ID)
    REFERENCES SYS_RIG(RIG_ID,SITE_ID),
  CONSTRAINT FK_JSA_COPY_ACTOR FOREIGN KEY (COPIED_BY_USER_ID)
    REFERENCES SYS_USER(USER_ID),
  CONSTRAINT FK_JSA_COPY_CREATED_SITE FOREIGN KEY (CREATED_SITE_ID)
    REFERENCES SYS_SITE(SITE_ID),
  CONSTRAINT CHK_JSA_COPY_DISTINCT CHECK (SOURCE_JSA_ID<>DESTINATION_JSA_ID),
  CONSTRAINT CHK_JSA_COPY_REASON CHECK (
    LENGTH(TRIM(COPY_REASON)) BETWEEN 1 AND 1000
  ),
  CONSTRAINT CHK_JSA_COPY_REQUEST_KEY CHECK (
    LENGTH(TRIM(REQUEST_KEY)) BETWEEN 1 AND 128
  ),
  CONSTRAINT CHK_JSA_COPY_REQUEST_HASH CHECK (
    REGEXP_LIKE(REQUEST_HASH,'^[0-9a-f]{64}$')
  )
);

CREATE INDEX IX_JSA_COPY_SOURCE
  ON JSA_COPY_PROVENANCE(SOURCE_JSA_ID,SOURCE_VERSION_ID,COPIED_AT);
CREATE INDEX IX_JSA_COPY_TIME
  ON JSA_COPY_PROVENANCE(COPIED_AT,COPY_PROVENANCE_ID);

/

CREATE OR REPLACE TRIGGER TRG_JSA_COPY_PROV_IMMUTABLE
BEFORE UPDATE OR DELETE ON JSA_COPY_PROVENANCE
FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20071,'JSA copy provenance is immutable');
END;
/
