CREATE OR REPLACE TRIGGER TRG_JSA_OFFICIAL_NUM_IMMUTABLE
BEFORE UPDATE OF JSA_NUMBER,NUMBER_SCOPE_KEY,NUMBER_STATUS ON JSA_MASTER
FOR EACH ROW
DECLARE
  V_BASE_NUMBER VARCHAR2(100 CHAR);
  V_CURRENT_REVISION NUMBER;
  V_EXPECTED_NUMBER VARCHAR2(100 CHAR);
  V_PUBLICATION_COUNT NUMBER;
BEGIN
  IF :OLD.NUMBER_STATUS='OFFICIAL' THEN
    IF :NEW.NUMBER_SCOPE_KEY<>:OLD.NUMBER_SCOPE_KEY
       OR :NEW.NUMBER_STATUS<>:OLD.NUMBER_STATUS
    THEN
      RAISE_APPLICATION_ERROR(-20068,'Official JSA number is immutable');
    END IF;

    IF :NEW.JSA_NUMBER<>:OLD.JSA_NUMBER THEN
      IF REGEXP_LIKE(:OLD.JSA_NUMBER,'\.[0-9]+$') THEN
        V_BASE_NUMBER := REGEXP_REPLACE(:OLD.JSA_NUMBER,'\.[0-9]+$','');
        V_CURRENT_REVISION := TO_NUMBER(REGEXP_SUBSTR(:OLD.JSA_NUMBER,'[0-9]+$'));
      ELSE
        V_BASE_NUMBER := :OLD.JSA_NUMBER;
        V_CURRENT_REVISION := 0;
      END IF;

      V_EXPECTED_NUMBER :=
        V_BASE_NUMBER || '.' || TO_CHAR(V_CURRENT_REVISION + 1,'FM9999999990');

      SELECT COUNT(*)
      INTO V_PUBLICATION_COUNT
      FROM JSA_VERSION W
      JOIN JSA_VERSION C
        ON C.JSA_VERSION_ID=:OLD.CURRENT_VERSION_ID
       AND C.VERSION_STATUS='PUBLISHED'
      JOIN JSA_WORKFLOW_INSTANCE I
        ON I.JSA_ID=:OLD.JSA_ID
       AND I.JSA_VERSION_ID=W.JSA_VERSION_ID
       AND I.INSTANCE_STATUS='ACTIVE'
      WHERE W.JSA_VERSION_ID=:OLD.WORKING_VERSION_ID
        AND W.BASE_VERSION_ID=:OLD.CURRENT_VERSION_ID
        AND NOT EXISTS (
          SELECT 1
          FROM JSA_WORKFLOW_TASK T
          WHERE T.INSTANCE_ID=I.INSTANCE_ID
            AND T.CYCLE_NUMBER=I.CYCLE_NUMBER
            AND T.TASK_STATUS='PENDING'
        );

      IF :NEW.JSA_NUMBER<>V_EXPECTED_NUMBER OR V_PUBLICATION_COUNT<>1 THEN
        RAISE_APPLICATION_ERROR(
          -20068,
          'Official JSA number is immutable outside governed replacement publication'
        );
      END IF;
    END IF;
  END IF;
END;
/
