import { JsaDraftValidationService } from '../src/modules/jsa-draft/application/jsa-draft-validation.service';
import type { JsaDraftDetail } from '@jsams/shared-types';
const service=new JsaDraftValidationService();
const draft=():JsaDraftDetail=>({jsaId:'1',versionId:'2',jsaNumber:'T-1',lifecycleStatus:'DRAFT',versionStatus:'DRAFT',ownerSiteId:'1',rigId:'2',departmentId:'3',jobTypeId:'4',matrixVersionId:'5',creatorUserId:'6',rowVersion:'1',versionRowVersion:'1',ptwRequired:false,prompts:[],tasks:[],basicSteps:[],promptCoverage:[],procedureReferences:[],attachments:[],editable:true,matrix:{id:'5',matrixId:'1',matrixCode:'M',matrixName:'Mixed',dimension:5,versionCode:'V1',active:true,immutable:true,rowVersion:'1',likelihoods:[],severities:[],results:[],cells:[],completeness:{complete:true,expectedCellCount:25,actualCellCount:25,missingCells:[],errors:[]}}});
describe('JSA Draft validation',()=>{
  it('groups incomplete draft errors by business section',()=>{const result=service.validate(draft());expect(result.valid).toBe(false);expect(new Set(result.errors.map(x=>x.section))).toEqual(new Set(['GENERAL','RISK','BASIC_STEPS']));});
  it('blocks prohibited residual risk and uncovered selected prompts',()=>{const value=draft();value.jobTitle='Job';value.tasks=[{id:'10',logicalKey:'10',title:'Task',displayOrder:1,rowVersion:'1',hazards:[{id:'11',logicalKey:'11',text:'Hazard',displayOrder:1,rowVersion:'1',controls:[{id:'12',logicalKey:'12',text:'Control',displayOrder:1,rowVersion:'1'}],initialRisk:{cellId:'1'},residualRisk:{cellId:'2',prohibited:true}}]}];value.prompts=[{id:'20',logicalKey:'20',promptId:'1',code:'P',label:'Prompt',selected:true,rowVersion:'1'}];value.basicSteps=[{id:'30',logicalKey:'30',text:'Step',displayOrder:1,noToolRequired:true,performers:[{id:'31',logicalKey:'31',positionId:'1',code:'P',name:'Performer',displayOrder:1,rowVersion:'1'}],supervisors:[{id:'32',logicalKey:'32',positionId:'2',code:'S',name:'Supervisor',displayOrder:1,rowVersion:'1'}],tools:[],rowVersion:'1'}];const result=service.validate(value);expect(result.errors.map(x=>x.code)).toEqual(expect.arrayContaining(['RESIDUAL_RISK_PROHIBITED','PROMPT_COVERAGE_REQUIRED']));});
  it('rejects task cycles and no-tool conflicts during structural save',()=>{expect(()=>service.structural({versionRowVersion:'1',prompts:[],coverage:[],procedureReferences:[],attachments:[],tasks:[{ref:'a',parentRef:'b',title:'A',displayOrder:1,hazards:[]},{ref:'b',parentRef:'a',title:'B',displayOrder:2,hazards:[]}],basicSteps:[]})).toThrow('cycle');expect(()=>service.structural({versionRowVersion:'1',prompts:[],coverage:[],procedureReferences:[],attachments:[],tasks:[],basicSteps:[{ref:'s',text:'S',displayOrder:1,noToolRequired:true,performers:[],supervisors:[],tools:[{ref:'t',toolId:'1',displayOrder:1}]}]})).toThrow('No tool required');});
});
